{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "6c4e583e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: langgraph[mermaid] in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (0.6.7)\n",
      "\u001b[33mWARNING: langgraph 0.6.7 does not provide the extra 'mermaid'\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: langchain-core>=0.1 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (0.3.75)\n",
      "Requirement already satisfied: langgraph-checkpoint<3.0.0,>=2.1.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (2.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<0.7.0,>=0.6.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (0.6.4)\n",
      "Requirement already satisfied: langgraph-sdk<0.3.0,>=0.2.2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (0.2.6)\n",
      "Requirement already satisfied: pydantic>=2.7.4 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (2.11.7)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph[mermaid]) (3.5.0)\n",
      "Requirement already satisfied: ormsgpack>=1.10.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph-checkpoint<3.0.0,>=2.1.0->langgraph[mermaid]) (1.10.0)\n",
      "Requirement already satisfied: httpx>=0.25.2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.10.1 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (3.11.3)\n",
      "Requirement already satisfied: anyio in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (4.10.0)\n",
      "Requirement already satisfied: certifi in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (2025.8.3)\n",
      "Requirement already satisfied: httpcore==1.* in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (1.0.9)\n",
      "Requirement already satisfied: idna in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (3.10)\n",
      "Requirement already satisfied: h11>=0.16 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (0.16.0)\n",
      "Requirement already satisfied: langsmith>=0.3.45 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (0.4.27)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (9.1.2)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (1.33)\n",
      "Requirement already satisfied: PyYAML>=5.3 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (6.0.2)\n",
      "Requirement already satisfied: typing-extensions>=4.7 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (4.15.0)\n",
      "Requirement already satisfied: packaging>=23.2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langchain-core>=0.1->langgraph[mermaid]) (25.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from jsonpatch<2.0,>=1.33->langchain-core>=0.1->langgraph[mermaid]) (3.0.0)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langsmith>=0.3.45->langchain-core>=0.1->langgraph[mermaid]) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langsmith>=0.3.45->langchain-core>=0.1->langgraph[mermaid]) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from langsmith>=0.3.45->langchain-core>=0.1->langgraph[mermaid]) (0.24.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from pydantic>=2.7.4->langgraph[mermaid]) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.33.2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from pydantic>=2.7.4->langgraph[mermaid]) (2.33.2)\n",
      "Requirement already satisfied: typing-inspection>=0.4.0 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from pydantic>=2.7.4->langgraph[mermaid]) (0.4.1)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from requests>=2.0.0->langsmith>=0.3.45->langchain-core>=0.1->langgraph[mermaid]) (3.4.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from requests>=2.0.0->langsmith>=0.3.45->langchain-core>=0.1->langgraph[mermaid]) (2.5.0)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (1.3.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in /Users/jinheewon/Library/Python/3.9/lib/python/site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph[mermaid]) (1.3.1)\n"
     ]
    }
   ],
   "source": [
    "!pip install \"langgraph[mermaid]\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "2725dff2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "✅ Central Router Agent compiled successfully!\n",
      "Could not generate graph image: Install pygraphviz to draw graphs: `pip install pygraphviz`.\n"
     ]
    }
   ],
   "source": [
    "# ==== 1번 셀: 중앙 라우터 방식 최종 코드 (모든 문제 해결 버전) ==\n",
    "\n",
    "import os\n",
    "import json\n",
    "from typing import TypedDict, Annotated, List, Dict, Any\n",
    "from IPython.display import Image, display\n",
    "from langchain_core.messages import BaseMessage, HumanMessage, ToolMessage, AIMessage\n",
    "from langgraph.graph import StateGraph, END\n",
    "from langgraph.checkpoint.memory import InMemorySaver\n",
    "from langchain_google_genai import ChatGoogleGenerativeAI\n",
    "from tavily import TavilyClient\n",
    "\n",
    "# ==========================================================\n",
    "# ✨ 1. AgentState 및 전문가 노드/Tool 정의 ✨\n",
    "# ==========================================================\n",
    "class AgentState(TypedDict):\n",
    "    messages: Annotated[List[BaseMessage], lambda x, y: x + y]\n",
    "    next_node: str\n",
    "    response_type: str\n",
    "    memory_summary: str\n",
    "\n",
    "  # === 컨텍스트 윈도우/서머리 예산 ===\n",
    "CONTEXT_BUDGET_TOKENS = 8000       # 프롬프트에 실을 '최근 대화' 토큰 예산\n",
    "SUMMARIZE_AT_TOKENS   = 12000      # 이 이상 커지면 오래된 구간을 요약해 memory_summary에 축약\n",
    "SUMMARY_MAX_TOKENS    = 600        # 러닝 서머리 길이 목표(LLM에 요청)\n",
    "\n",
    "\n",
    "# ==== 환경 설정, 모델 로딩, Tool 정의 ====\n",
    "def setup_environment():\n",
    "    # 💥 중요: \"tvly-...\" 부분에 본인의 Tavily API 키를 입력하세요.\n",
    "    TAVILY_API_KEY = \"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\"\n",
    "    os.environ[\"TAVILY_API_KEY\"] = TAVILY_API_KEY\n",
    "    return TavilyClient(api_key=TAVILY_API_KEY)\n",
    "\n",
    "tavily_client = setup_environment()\n",
    "\n",
    "# 🤫 제공해주신 본인의 Gemini API 키를 \"\" 안에 붙여넣으세요.\n",
    "# (보안을 위해 이 키는 나중에 꼭 교체해주세요!)\n",
    "GOOGLE_API_KEY = \"AIzaSyAymOmcEDUuV9xWZ-o_3ecIkRrlR8P6I5E\"\n",
    "\n",
    "# ✨ 모델을 초기화할 때 위 API 키를 직접 전달합니다.\n",
    "model = ChatGoogleGenerativeAI(\n",
    "    model=\"gemini-1.5-flash\",\n",
    "    google_api_key=GOOGLE_API_KEY\n",
    ")\n",
    "\n",
    "json_model = ChatGoogleGenerativeAI(\n",
    "    model=\"gemini-1.5-flash\",\n",
    "    model_kwargs={\"response_mime_type\": \"application/json\"},\n",
    "    google_api_key=GOOGLE_API_KEY\n",
    ")\n",
    "\n",
    "# ✨ 헬퍼\n",
    "def _approx_tokens(text: str) -> int:\n",
    "    # 대략 4문자 ≈ 1토큰 가정 (모델 무관 근사치)\n",
    "    if not text:\n",
    "        return 0\n",
    "    return max(1, len(text) // 4)\n",
    "\n",
    "def _build_serialized_history(messages: List[BaseMessage]) -> str:\n",
    "    \"\"\"모든 메시지를 직렬화 (요약 트리거 계산용)\"\"\"\n",
    "    lines = []\n",
    "    for m in messages:\n",
    "        if isinstance(m, HumanMessage):\n",
    "            lines.append(f\"User: {m.content}\")\n",
    "        elif isinstance(m, AIMessage):\n",
    "            if not getattr(m, \"tool_calls\", []):\n",
    "                lines.append(f\"Assistant: {m.content}\")\n",
    "    return \"\\n\".join(lines)\n",
    "\n",
    "def _get_conversation_history_windowed(state: AgentState, budget_tokens: int = CONTEXT_BUDGET_TOKENS) -> str:\n",
    "    \"\"\"\n",
    "    memory_summary(러닝 서머리) + 최근 대화만 모아\n",
    "    LLM에 넣을 컨텍스트 문자열을 만든다.\n",
    "    \"\"\"\n",
    "    recent_blocks: List[str] = []\n",
    "    used = 0\n",
    "    # 최신부터 거꾸로 모으면서 예산 소진 시 중단\n",
    "    for m in reversed(state[\"messages\"]):\n",
    "        # Human/AI만 최근 대화에 포함 (툴콜 내용은 제외)\n",
    "        if isinstance(m, HumanMessage):\n",
    "            s = f\"User: {m.content}\"\n",
    "        elif isinstance(m, AIMessage) and not getattr(m, \"tool_calls\", []):\n",
    "            s = f\"Assistant: {m.content}\"\n",
    "        else:\n",
    "            continue\n",
    "        t = _approx_tokens(s)\n",
    "        if used + t > budget_tokens:\n",
    "            break\n",
    "        recent_blocks.append(s)\n",
    "        used += t\n",
    "\n",
    "    recent_part = \"\\n\".join(reversed(recent_blocks)).strip()\n",
    "    summary_part = (state.get(\"memory_summary\") or \"\").strip()\n",
    "    if summary_part and recent_part:\n",
    "        return f\"[SUMMARY]\\n{summary_part}\\n\\n[RECENT]\\n{recent_part}\"\n",
    "    elif summary_part:\n",
    "        return f\"[SUMMARY]\\n{summary_part}\"\n",
    "    else:\n",
    "        return recent_part\n",
    "\n",
    "from typing import Optional\n",
    "\n",
    "def _maybe_update_memory_summary(state: AgentState) -> Optional[str]:\n",
    "    \"\"\"\n",
    "    대화가 SUMMARIZE_AT_TOKENS를 넘으면,\n",
    "    '오래된 구간'을 요약해 memory_summary에 누적한다.\n",
    "    반환값: 갱신된 summary 문자열(없으면 None)\n",
    "    \"\"\"\n",
    "    full = _build_serialized_history(state[\"messages\"])\n",
    "    if _approx_tokens(full) < SUMMARIZE_AT_TOKENS:\n",
    "        return None  # 아직 여유 있음\n",
    "\n",
    "    # 오래된 절반 정도를 요약 대상으로 잡는다\n",
    "    # (필요하면 더 정교한 분할 로직으로 바꿔도 됨)\n",
    "    midpoint = max(1, len(full) * 6 // 10)  # 앞쪽 60% 근사\n",
    "    old_chunk = full[:midpoint]\n",
    "    keep_chunk = full[midpoint:]  # 최근부\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "당신은 대화 러닝 서머리 요약기입니다.\n",
    "아래 '오래된 대화'를 읽고, 앞으로의 작업에 필요한 핵심만 한국어로 간결하게 요약하세요.\n",
    "- 사용자 선호/제약(예산, 일정, 선호 스타일)\n",
    "- 이미 내려진 결정/합의\n",
    "- 해결된/미해결 이슈, 액션아이템\n",
    "- 불필요한 잡담/중복 제거\n",
    "- {SUMMARY_MAX_TOKENS} 토큰 이내 목표\n",
    "\n",
    "[오래된 대화]\n",
    "{old_chunk}\n",
    "\"\"\"\n",
    "    try:\n",
    "        summary = model.invoke(prompt).content.strip()\n",
    "    except Exception:\n",
    "        summary = \"\"\n",
    "\n",
    "    # 이전 요약과 합치기 (중복 최소화는 단순 연결로 처리)\n",
    "    prev = (state.get(\"memory_summary\") or \"\").strip()\n",
    "    new_summary = (prev + \"\\n\" + summary).strip() if summary else prev or \"\"\n",
    "\n",
    "    # keep_chunk 자체는 상태(messages)에 그대로 남아있지만,\n",
    "    # 프롬프트 구성은 windowed 함수가 담당하므로 문제 없음.\n",
    "    return new_summary or None\n",
    "\n",
    "\n",
    "def _get_conversation_history(state: AgentState) -> str:\n",
    "    \"\"\"메시지 기록 전체를 하나의 대화 문자열로 결합합니다. (장기 기억 역할)\"\"\"\n",
    "    history = []\n",
    "    for msg in state[\"messages\"]:\n",
    "        if isinstance(msg, HumanMessage):\n",
    "            history.append(f\"User: {msg.content}\")\n",
    "        elif isinstance(msg, AIMessage):\n",
    "            if not getattr(msg, 'tool_calls', []):\n",
    "                history.append(f\"Assistant: {msg.content}\")\n",
    "    return \"\\n\".join(history)\n",
    "\n",
    "def _get_last_user_message(state: AgentState) -> str:\n",
    "    \"\"\"가장 최근 Human 메시지의 content만 반환 (토픽 섞임 방지용)\"\"\"\n",
    "    for msg in reversed(state[\"messages\"]):\n",
    "        if isinstance(msg, HumanMessage):\n",
    "            return msg.content\n",
    "    return \"\"\n",
    "\n",
    "def is_ambiguous_with_llm(query: str) -> bool:\n",
    "    \"\"\"Judges whether the user's request is ambiguous using an LLM.\"\"\"\n",
    "    print(f\"\\n[LLM Check] 🤖 Is the conversation ambiguous?\\n--- Conversation ---\\n{query}\\n--------------------\")\n",
    "    system_prompt = \"\"\"\n",
    "    You are an expert at judging the ambiguity of user requests.\n",
    "    Based on the entire conversation history, you must determine if the information is specific enough to carry out the user's final goal.\n",
    "\n",
    "    <Criteria>\n",
    "    - A user's first question is ambiguous if it is too broad, lacking a subject, target, or purpose (e.g., \"Write a report\").\n",
    "    - Even if the user has provided an answer, the request is still ambiguous if key information required to start the task is still missing.\n",
    "    - If the conversation has progressed enough that a concrete plan can be created, it is no longer ambiguous.\n",
    "\n",
    "    <Examples>\n",
    "    - Conversation: \"User: Write a report\" -> Ambiguous (What is the topic?)\n",
    "    - Conversation: \"User: Write a report\\nAssistant: What is the topic?\\nUser: A marketing analysis report\" -> Still ambiguous (What product? For whom?)\n",
    "    - Conversation: \"User: Write a marketing analysis report on the new robot vacuum sold on Coupang for the executive team.\" -> Specific (not ambiguous)\n",
    "\n",
    "    Analyze the user's request and respond ONLY in the following JSON format.\n",
    "    {\"is_ambiguous\": boolean, \"reason\": \"The reason for your judgment.\"}\n",
    "    \"\"\"\n",
    "    try:\n",
    "        response = json_model.invoke(system_prompt + f\"\\n\\nConversation History:\\n\\\"{query}\\\"\")\n",
    "        content = response.content.strip()\n",
    "        # 모델이 마크다운으로 응답할 경우를 대비한 전처리\n",
    "        if content.startswith(\"```json\"):\n",
    "            content = content.strip(\"```json\").strip(\"```\").strip()\n",
    "        result = json.loads(content)\n",
    "        is_ambiguous = result.get(\"is_ambiguous\", True)\n",
    "        reason = result.get(\"reason\", \"No reason provided.\")\n",
    "        print(f\"Decision: Ambiguous = {is_ambiguous} (Reason: {reason})\")\n",
    "        return is_ambiguous\n",
    "    except Exception as e:\n",
    "        print(f\"Error during ambiguity check: {e}\")\n",
    "        return True  # On error, default to QA node for safety\n",
    "\n",
    "def _generate_search_query_with_llm(plan_description: str, conversation_history: str) -> str:\n",
    "    \"\"\"LLM을 사용하여 계획 설명을 효율적인 검색어로 변환합니다.\"\"\"\n",
    "    print(f\"\\n[LLM Check] ➡️ Optimizing search query: '{plan_description}'\")\n",
    "    system_prompt = \"\"\"\n",
    "    You are an expert at converting a detailed research plan description and a full conversation history into a concise and effective search engine query.\n",
    "\n",
    "    <Instructions>\n",
    "    - Analyze the user's intent from the full conversation history and the plan description.\n",
    "    - Extract key nouns, verbs, and phrases, such as specific locations, travel styles, and interests.\n",
    "    - Omit conversational filler words and unnecessary phrases.\n",
    "    - Translate the query to Korean if necessary.\n",
    "    - The final query should be short, specific, and optimized for a search engine.\n",
    "    - If the user's intent is a travel plan, the query must include the destination (e.g., \"도쿄\", \"오사카\") and specific keywords from the conversation history (e.g., \"저렴한 숙소\", \"맛집\", \"관광지\"). If no location is mentioned, assume \"도쿄\".\n",
    "\n",
    "    <Examples>\n",
    "    - Description: \"저렴한 비용으로 즐길 수 있는 주요 관광지 목록을 찾습니다.\" (대화: '일본 여행 계획', '저렴하게') -> \"일본 저렴한 관광지\"\n",
    "    - Description: \"숙박 시설을 검색하고 예약 정보를 수집합니다.\" (대화: '도쿄 여행', '호텔') -> \"도쿄 저렴한 호텔\"\n",
    "    - Description: \"3일간의 휴식 코스\" (대화: '오사카 여행', '3일', '휴식') -> \"오사카 3일 휴식 코스\"\n",
    "\n",
    "    Return ONLY the final, optimized search query as a plain string.\n",
    "    \"\"\"\n",
    "    response = model.invoke(system_prompt + f\"\\n\\nPlan Description: \\\"{plan_description}\\\"\\nConversation History: \\\"{conversation_history}\\\"\")\n",
    "    optimized_query = response.content.strip()\n",
    "    print(f\"Decision: Optimized query = '{optimized_query}'\")\n",
    "    return optimized_query\n",
    "\n",
    "def classify_intent_with_llm(query: str) -> str:\n",
    "    \"\"\"LLM을 사용하여 사용자의 요청 의도를 'search' 또는 'report'로 분류합니다.\"\"\"\n",
    "    print(f\"\\n[LLM Check] 🎯 Classifying intent for: '{query}'\")\n",
    "    system_prompt = \"\"\"\n",
    "    You are an expert at classifying user requests.\n",
    "    Based on the user's request, you must classify the intent into one of two categories.\n",
    "\n",
    "    <Categories>\n",
    "    - 'search': The user wants to find or retrieve specific information, articles, facts, or data. They do not require a detailed, structured, or synthesized document.\n",
    "    - 'report': The user wants a comprehensive, structured document that synthesizes information from multiple sources, such as a report, analysis, summary, plan, or detailed article.\n",
    "\n",
    "    <Examples>\n",
    "    - User Request: \"최근 인플레이션에 대한 뉴스 기사를 찾아줘\" -> 'search'\n",
    "    - User Request: \"토스 기업의 재무 성과에 대한 최신 기사들을 알려줘\" -> 'search'\n",
    "    - User Request: \"2024년 한국 경제 동향에 대한 보고서를 작성해줘\" -> 'report'\n",
    "    - User Request: \"챗GPT-4o와 Gemini 1.5 Pro의 성능을 비교 분석하는 문서를 만들어줘\" -> 'report'\n",
    "    - User Request: \"한국의 인공지능 산업 발전 로드맵을 정리해줘\" -> 'report'\n",
    "\n",
    "    Analyze the user's request and respond ONLY with the category name ('search' or 'report').\n",
    "    \"\"\"\n",
    "    response = model.invoke(system_prompt + f\"\\n\\nUser Request:\\n\\\"{query}\\\"\")\n",
    "    intent = response.content.strip().lower()\n",
    "    print(f\"Decision: Intent = {intent}\")\n",
    "    return intent\n",
    "\n",
    "# --- [전체 코드-1] QA Tool 정의 ---\n",
    "# --- [전체 코드-1] QA Tool 정의 ---\n",
    "# --- [전체 코드-1] QA Tool 정의 ---\n",
    "def generate_clarifying_question_tool(query: str) -> List[dict]:\n",
    "    \"\"\"사용자의 요청이 모호할 경우, 명확화를 위해 되물을 질문과 선택지를 생성합니다.\"\"\"\n",
    "    # ✨ 추가된 부분 ✨\n",
    "    # global json_model_with_parser  # 이 줄은 필요 없으니 삭제하거나 주석 처리\n",
    "    print(f\"\\n[Tool Call] ❓ generate_clarifying_question_tool: '{query}'\")\n",
    "    response_data = None\n",
    "    system_prompt = \"\"\"\n",
    "    You are a proactive assistant that helps users accomplish their goals by gathering essential information.\n",
    "    Your task is to identify key missing pieces of information in the user's request and ask concise, clear questions to get that information.\n",
    "    The response must be in a specific JSON format. Do not add any extra text or explanations.\n",
    "    \n",
    "    <Criteria for a Good Clarifying Question>\n",
    "    - The question should be specific, not general.\n",
    "    - Provide at least 3 multiple-choice options for the user to select from.\n",
    "    - If the user's request is a travel plan, ask about duration, budget, or preferred location.\n",
    "    - If the user's request is for a report or analysis, ask about the target audience, purpose, or specific scope.\n",
    "    \n",
    "    <Output Format>\n",
    "    Return a JSON array of objects. Each object represents a question.\n",
    "    [\n",
    "      {\"question\": \"What is the primary topic of your request?\", \"choices\": [\"Report on technology trends\", \"Analysis of market share\", \"Comparison of two products\"]},\n",
    "      {\"question\": \"Who is the target audience for this document?\", \"choices\": [\"Executive team\", \"Marketing department\", \"General public\"]},\n",
    "      ...\n",
    "    ]\n",
    "    <Critical Requirements>\n",
    "    - NO extra metadata, explanations, or wrapper objects.\n",
    "    - Return pure JSON only.\n",
    "    \"\"\"\n",
    "    user_prompt = f'userInput: \"{query}\"'\n",
    "    try:\n",
    "        # ⚠️ 이 부분을 수정합니다: json_model_with_parser -> json_model\n",
    "        response = json_model.invoke(\n",
    "            system_prompt + \"\\n\\n\" + user_prompt\n",
    "        )\n",
    "        content = response.content.strip()\n",
    "        # 모델이 마크다운으로 응답할 경우를 대비한 전처리\n",
    "        if content.startswith(\"```json\"):\n",
    "            content = content.strip(\"```json\").strip(\"```\").strip()\n",
    "        return json.loads(content)\n",
    "    except json.JSONDecodeError as e:\n",
    "        print(f\"⚠️ JSON 파싱 실패: {e}\")\n",
    "        return [{\"question\": \"요청을 명확히 하기 위해 어떤 정보를 더 제공해야 할까요?\", \"choices\": [\"목적\", \"대상\", \"예산\", \"기간\"]}]\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ 예상치 못한 오류 발생: {e}\")\n",
    "        return [{\"question\": f\"요청 처리 중 오류가 발생했습니다. (오류: {e})\", \"choices\": [\"예\", \"아니오\"]}]\n",
    "\n",
    "\n",
    "# --- [전체 코드-2] Plan Tool 정의 ---\n",
    "def create_plan_tool(query: str) -> List[Dict[str, Any]]:\n",
    "    \"\"\"명확해진 사용자 요청을 바탕으로, 구조화된 리서치 계획을 JSON 객체 배열로 생성합니다.\"\"\"\n",
    "    print(f\"\\n[Tool Call] 📝 create_plan_tool (Advanced): '{query}'\")\n",
    "    system_prompt = \"\"\"\n",
    "You are a planner that must always return a valid JSON array where each step is a separate object.\n",
    "<planning_rules>\n",
    "1. Break down the user request into clear, actionable steps for research.\n",
    "2. Each step MUST be its own object in an array.\n",
    "3. MAXIMUM 10 steps allowed - create high-level phases for complex tasks.\n",
    "4. Steps should be logically ordered and atomic (one clear action per step).\n",
    "5. Number steps sequentially starting from 1.\n",
    "6. Set dependencies only when a step genuinely cannot start without another step completing.\n",
    "</planning_rules>\n",
    "<output_format>\n",
    "Return ONLY a JSON array of step objects:\n",
    "[\n",
    "  {\n",
    "    \"id\": 1,\n",
    "    \"title\": \"Clear, actionable step title\",\n",
    "    \"description\": \"Detailed explanation of what needs to be done in this step\",\n",
    "    \"status\": \"pending\",\n",
    "    \"research\": true,\n",
    "    \"dependencies\": [],\n",
    "    \"complexity\": 3\n",
    "  }\n",
    "]\n",
    "</output_format>\n",
    "<critical_requirements>\n",
    "- NO extra metadata, explanations, or wrapper objects.\n",
    "- Return pure JSON only.\n",
    "</critical_requirements>\n",
    "\"\"\"\n",
    "    response = json_model.invoke(system_prompt + f\"\\n\\nUser Request: \\\"{query}\\\"\")\n",
    "    try:\n",
    "        content = response.content.strip()\n",
    "        # 마크다운 래퍼 제거\n",
    "        if content.startswith(\"```json\"):\n",
    "            content = content.strip(\"```json\").strip(\"```\")\n",
    "        return json.loads(content)\n",
    "    except (json.JSONDecodeError, ValueError) as e:\n",
    "        print(f\"⚠️ Warning: create_plan_tool failed to return valid JSON: {e}\")\n",
    "        # 오류 발생 시 빈 리스트 대신 None을 반환하거나, 에러를 던져 상위 노드에서 처리하도록 할 수 있음\n",
    "        return None \n",
    "\n",
    "# --- [전체 코드-3] Web Search Tool 정의 ---\n",
    "def web_search_tool(query: str) -> List[Dict[str, Any]]:\n",
    "    print(f\"\\n[Tool Call] 🔍 web_search_tool: '{query}'\")\n",
    "    try:\n",
    "        search_results = tavily_client.search(query, search_depth=\"advanced\", max_results=3)\n",
    "        print(f\"🔍 Tavily API Raw Response: {search_results}\")\n",
    "        return search_results.get('results', []) or []\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ Tavily error: {e}\")\n",
    "        return []\n",
    "\n",
    "# --- [전체 코드-4] Draft Tool 정의 ---\n",
    "def generate_draft_tool(research_results: List[str], query: str) -> str:\n",
    "    \"\"\"사용자 요청과 리서치 결과를 바탕으로 최종 보고서 초안을 작성합니다.\"\"\"\n",
    "    print(f\"\\n[Tool Call] ✍️ generate_draft_tool: '{query}'\")\n",
    "    results_str = \"\\n\\n\".join(research_results)\n",
    "    prompt = f\"\"\"\n",
    "You are an expert report writer.\n",
    "Based on the user's request and the following research results, write a detailed, structured draft.\n",
    "\n",
    "<User Request>\n",
    "{query}\n",
    "\n",
    "<Research Results>\n",
    "{results_str}\n",
    "\n",
    "<Instructions>\n",
    "- Write in Korean\n",
    "- Use headings and bullet points if appropriate\n",
    "- Be clear and concise\n",
    "- Include factual information only from the research results\n",
    "\"\"\"\n",
    "    response = model.invoke(prompt)\n",
    "    return response.content\n",
    "\n",
    "def reflect_and_critique_tool(conversation: str) -> str:\n",
    "    print(f\"\\n[Tool Call] 🤔 reflect_and_critique_tool...\")\n",
    "    system_prompt = \"\"\"\n",
    "    ... (기존 시스템 프롬프트 내용) ...\n",
    "    \"\"\"\n",
    "    \n",
    "    # ✨ 추가된 부분 ✨\n",
    "    full_prompt = system_prompt + f\"\\n\\nConversation History:\\n\\\"{conversation}\\\"\"\n",
    "    print(\"--- 비평 생성용 LLM 프롬프트 ---\")\n",
    "    print(full_prompt)\n",
    "    print(\"---------------------------------\")\n",
    "    \n",
    "    response = model.invoke(full_prompt)\n",
    "    \n",
    "    # ✨ 추가된 부분 ✨\n",
    "    print(\"--- LLM의 원본 비평 응답 ---\")\n",
    "    print(response.content)\n",
    "    print(\"---------------------------------\")\n",
    "\n",
    "    return response.content\n",
    "# ==========================================================\n",
    "# ✨ 1. 전문가 노드 구현 ✨\n",
    "# ==========================================================\n",
    "# 수정된 qa_node 함수\n",
    "def qa_node(state: AgentState):\n",
    "    print(\"\\n--- Node: ❓ QA Specialist ---\")\n",
    "    # ✅ 전체 대화 기록을 기반으로 질문 생성하도록 변경\n",
    "    conversation_history = _get_conversation_history_windowed(state)\n",
    "    questions = generate_clarifying_question_tool(conversation_history)\n",
    "    return {\n",
    "        \"messages\": [\n",
    "            ToolMessage(\n",
    "                name=\"generate_clarifying_question_tool\",\n",
    "                content=json.dumps(questions, ensure_ascii=False),\n",
    "                tool_call_id=\"manual_qa\"\n",
    "            )\n",
    "        ]\n",
    "    }\n",
    "\n",
    "def planner_node(state: AgentState):\n",
    "    print(\"\\n--- Node: 📝 Planning Specialist ---\")\n",
    "    # ✅ 토픽 섞임 방지: 마지막 사용자 메시지만 기반으로 플랜 생성\n",
    "    last_user = _get_last_user_message(state)\n",
    "    plan = create_plan_tool(last_user)\n",
    "    cleaned = []\n",
    "    for step in (plan or []):\n",
    "        if isinstance(step, dict):\n",
    "            step = {**step}\n",
    "            # ✅ 기본적으로 research는 True 유지 (툴이 지정했으면 그 값 사용)\n",
    "            step[\"research\"] = bool(step.get(\"research\", True))\n",
    "            cleaned.append(step)\n",
    "    return {\n",
    "        \"messages\": [\n",
    "            ToolMessage(\n",
    "                name=\"create_plan_tool\",\n",
    "                content=json.dumps(cleaned, ensure_ascii=False),\n",
    "                tool_call_id=\"manual_planner\"\n",
    "            )\n",
    "        ]\n",
    "    }\n",
    "\n",
    "def researcher_node(state: AgentState):\n",
    "    print(\"\\n--- Node: 🔍 Research Specialist ---\")\n",
    "    # ToolMessage에서 계획(plan) 정보를 찾음\n",
    "    plan = []\n",
    "    for m in reversed(state[\"messages\"]):\n",
    "        if isinstance(m, ToolMessage) and m.name == \"create_plan_tool\":\n",
    "            try:\n",
    "                plan = json.loads(m.content) or []\n",
    "            except json.JSONDecodeError:\n",
    "                plan = []\n",
    "            break\n",
    "\n",
    "    # 전체 대화 기록은 질의 최적화의 보조로만 사용\n",
    "    conversation_history = _get_conversation_history_windowed(state)\n",
    "    all_search_results = []\n",
    "\n",
    "    has_research_step = False\n",
    "    if plan:\n",
    "        for step in plan:\n",
    "            if step.get(\"research\"):\n",
    "                has_research_step = True\n",
    "                optimized_query = _generate_search_query_with_llm(step.get(\"description\", \"\"), conversation_history)\n",
    "                print(f\"🔍 Executing search for: '{optimized_query}' (from step: '{step.get('title','')})'\")\n",
    "                results_list = web_search_tool(optimized_query)\n",
    "                if results_list:\n",
    "                    print(f\"✅ Found {len(results_list)} results for '{optimized_query}'\")\n",
    "                    all_search_results.extend(results_list)\n",
    "                else:\n",
    "                    print(f\"❌ No results found for '{optimized_query}'\")\n",
    "\n",
    "    # ✅ 플랜은 있는데 research 스텝이 하나도 없을 때 fallback 검색\n",
    "    if plan and not has_research_step:\n",
    "        seed = \" \".join([str(s.get(\"title\", \"\")) for s in plan[:3]]).strip()\n",
    "        if not seed:\n",
    "            seed = conversation_history[-200:]\n",
    "        optimized_query = _generate_search_query_with_llm(seed, conversation_history)\n",
    "        print(f\"🔍 Executing fallback search for: '{optimized_query}'\")\n",
    "        results_list = web_search_tool(optimized_query)\n",
    "        if results_list:\n",
    "            print(f\"✅ Fallback found {len(results_list)} results\")\n",
    "            all_search_results.extend(results_list)\n",
    "        else:\n",
    "            print(\"❌ Fallback search returned no results\")\n",
    "\n",
    "    # 플랜 자체가 없을 때는 전체 대화 기반 일반 검색 1회\n",
    "    if not plan:\n",
    "        optimized_query = _generate_search_query_with_llm(conversation_history, conversation_history)\n",
    "        print(f\"🔍 Executing general search for: '{optimized_query}'\")\n",
    "        all_search_results.extend(web_search_tool(optimized_query))\n",
    "\n",
    "    combined_results_json_str = json.dumps(all_search_results, ensure_ascii=False)\n",
    "    return {\n",
    "        \"messages\": [\n",
    "            ToolMessage(\n",
    "                content=combined_results_json_str,\n",
    "                name=\"web_search_tool\",\n",
    "                tool_call_id=\"manual_researcher\"\n",
    "            )\n",
    "        ]\n",
    "    }\n",
    "\n",
    "def generator_node(state: AgentState):\n",
    "    print(\"\\n--- Node: ✍️ Generation Specialist ---\")\n",
    "    conversation_history = _get_conversation_history_windowed(state)\n",
    "    research_results = []\n",
    "    plan = []\n",
    "\n",
    "    found_research = False\n",
    "    found_plan = False\n",
    "    for m in reversed(state[\"messages\"]):\n",
    "        if not found_research and isinstance(m, ToolMessage) and m.name == \"web_search_tool\":\n",
    "            try:\n",
    "                raw_results = json.loads(m.content)\n",
    "                if isinstance(raw_results, list):\n",
    "                    research_results = raw_results\n",
    "            except (json.JSONDecodeError, TypeError):\n",
    "                research_results = []\n",
    "            found_research = True\n",
    "\n",
    "        if not found_plan and isinstance(m, ToolMessage) and m.name == \"create_plan_tool\":\n",
    "            try:\n",
    "                raw_plan = json.loads(m.content)\n",
    "                if isinstance(raw_plan, list):\n",
    "                    plan = raw_plan\n",
    "            except (json.JSONDecodeError, TypeError):\n",
    "                plan = []\n",
    "            found_plan = True\n",
    "\n",
    "        if found_research and found_plan:\n",
    "            break\n",
    "\n",
    "    results_str = \"\\n\\n\".join(\n",
    "        [f\"Title: {r.get('title', 'N/A')}\\nURL: {r.get('url', 'N/A')}\\nContent: {r.get('content', 'N/A')}\" for r in research_results]\n",
    "    )\n",
    "\n",
    "    # 검색 결과가 비어있을 경우\n",
    "    if not results_str.strip():\n",
    "        if not plan or not any(step.get(\"research\") for step in plan):\n",
    "            response_content = \"죄송합니다. 요청하신 내용에 대한 검색 결과를 찾을 수 없습니다. 키워드를 변경해서 다시 시도해 주세요.\"\n",
    "            response_type = \"search_summary\"\n",
    "        else:\n",
    "            response_content = \"죄송합니다. 요청하신 내용을 기반으로 계획을 수립하기 위한 충분한 정보를 찾지 못했습니다. 보다 구체적인 정보를 제공해주시면 다시 시도해 보겠습니다.\"\n",
    "            response_type = \"report_draft\"\n",
    "        return {\n",
    "            \"messages\": [AIMessage(content=response_content)],\n",
    "            \"response_type\": response_type\n",
    "        }\n",
    "\n",
    "    # 결과가 있을 때\n",
    "    if not plan or not any(step.get(\"research\") for step in plan):\n",
    "        prompt = f\"\"\"\n",
    "        You are an expert at summarizing search results.\n",
    "        Based on the user's request and the following research results, provide a concise and factual summary in Korean. Do not add any new information.\n",
    "        <User Request>\n",
    "        {conversation_history}\n",
    "        <Research Results>\n",
    "        {results_str}\n",
    "        \"\"\"\n",
    "        response_type = \"search_summary\"\n",
    "    else:\n",
    "        prompt = f\"\"\"\n",
    "        You are an expert report writer.\n",
    "        Based on the user's request and the following research results, write a detailed, structured draft in Korean.\n",
    "        The draft should be a concrete plan or report, not just a summary.\n",
    "        <User Request>\n",
    "        {conversation_history}\n",
    "        <Research Results>\n",
    "        {results_str}\n",
    "        <Instructions>\n",
    "        - Write a detailed travel plan, structured by day (Day 1, Day 2, etc.) when applicable.\n",
    "        - Include specific attractions, restaurants, and activities when the topic is travel.\n",
    "        - Ensure the plan aligns with the user's constraints provided in the conversation history.\n",
    "        - Use headings and bullet points to make the plan easy to read.\n",
    "        - Be clear and concise.\n",
    "        - Include factual information only from the research results.\n",
    "        - If certain information is missing (e.g., a specific festival date), state this clearly and suggest a general plan.\n",
    "        </Instructions>\n",
    "        \"\"\"\n",
    "        response_type = \"report_draft\"\n",
    "\n",
    "    response = model.invoke(prompt)\n",
    "    state_update = {\n",
    "        \"messages\": [AIMessage(content=response.content)],\n",
    "        \"response_type\": response_type\n",
    "    }\n",
    "    return state_update\n",
    "\n",
    "def reflect_node(state: AgentState):\n",
    "    print(\"\\n--- Node: 🤔 Reflection Specialist ---\")\n",
    "    conversation_history = _get_conversation_history_windowed(state)\n",
    "    \n",
    "    # reflect_and_critique_tool을 호출하여 비평을 생성합니다.\n",
    "    critique = reflect_and_critique_tool(conversation_history)\n",
    "    \n",
    "    # ✨ 추가된 부분 ✨\n",
    "    print(\"\\n[생성된 비평 내용]\")\n",
    "    print(critique)\n",
    "    print(\"-----------------------------------\")\n",
    "    \n",
    "    final_response = f\"## 최종 보고서 초안:\\n{state['messages'][-1].content}\\n\\n## 검토 및 제언:\\n{critique}\"\n",
    "    return {\n",
    "        \"messages\": [AIMessage(content=final_response)],\n",
    "        \"response_type\": \"final\"\n",
    "    }\n",
    "\n",
    "# ==========================================================\n",
    "# ✨ 2. 중앙 라우터(PM) 노드 및 그래프 조립 ✨\n",
    "# ==========================================================\n",
    "def router_node(state: AgentState):\n",
    "    print(\"\\n--- Node: 🧑‍💼 Central Router (PM) ---\")\n",
    "    msgs = state[\"messages\"]\n",
    "\n",
    "    # ✅ 진입할 때 컨텍스트 과부하 방지 (러닝 서머리 갱신)\n",
    "    updates = {}\n",
    "    try:\n",
    "        new_sum = _maybe_update_memory_summary(state)\n",
    "        if new_sum is not None:\n",
    "            updates[\"memory_summary\"] = new_sum\n",
    "    except Exception as e:\n",
    "        print(f\"[summary] skip due to error: {e}\")\n",
    "\n",
    "    if isinstance(msgs[-1], HumanMessage):\n",
    "        conversation_history = _get_conversation_history_windowed(state)\n",
    "        if is_ambiguous_with_llm(conversation_history):\n",
    "            return {**updates, \"next_node\": \"qa\"}\n",
    "        intent = classify_intent_with_llm(conversation_history)\n",
    "        return {**updates, \"next_node\": \"researcher\" if intent == \"search\" else \"planner\"}\n",
    "\n",
    "    last = msgs[-1]\n",
    "    if isinstance(last, AIMessage):\n",
    "        if isinstance(last.content, str) and last.content.startswith(\"## 최종 보고서 초안:\"):\n",
    "            return {**updates, \"response_type\": \"final\", \"next_node\": \"end\"}\n",
    "\n",
    "        rt = state.get(\"response_type\")\n",
    "        if rt == \"final\" or rt == \"search_summary\":\n",
    "            return {**updates, \"next_node\": \"end\"}\n",
    "        if rt == \"report_draft\":\n",
    "            return {**updates, \"response_type\": \"reflecting\", \"next_node\": \"reflect\"}\n",
    "        if rt == \"reflecting\":\n",
    "            return {**updates, \"next_node\": \"end\"}\n",
    "        return {**updates, \"next_node\": \"end\"}\n",
    "\n",
    "    elif isinstance(last, ToolMessage):\n",
    "        if last.name == \"generate_clarifying_question_tool\":\n",
    "            return {**updates, \"next_node\": \"end\"}\n",
    "        elif last.name == \"create_plan_tool\":\n",
    "            return {**updates, \"next_node\": \"researcher\"}\n",
    "        elif last.name == \"web_search_tool\":\n",
    "            return {**updates, \"next_node\": \"generator\"}\n",
    "\n",
    "workflow = StateGraph(AgentState)\n",
    "workflow.add_node(\"router\", router_node)\n",
    "workflow.add_node(\"qa\", qa_node)\n",
    "workflow.add_node(\"planner\", planner_node)\n",
    "workflow.add_node(\"researcher\", researcher_node)\n",
    "workflow.add_node(\"generator\", generator_node)\n",
    "workflow.add_node(\"reflect\", reflect_node)\n",
    "\n",
    "workflow.set_entry_point(\"router\")\n",
    "workflow.add_conditional_edges(\n",
    "    \"router\",\n",
    "    lambda state: state[\"next_node\"],\n",
    "    {\n",
    "        \"qa\": \"qa\",\n",
    "        \"planner\": \"planner\",\n",
    "        \"researcher\": \"researcher\",\n",
    "        \"generator\": \"generator\",\n",
    "        \"reflect\": \"reflect\",\n",
    "        \"end\": END\n",
    "    }\n",
    ")\n",
    "\n",
    "# QA 노드를 제외한 모든 전문가는 일을 마치면 다시 Router에게 보고\n",
    "workflow.add_edge(\"planner\", \"router\")\n",
    "workflow.add_edge(\"researcher\", \"router\")\n",
    "workflow.add_edge(\"generator\", \"router\")\n",
    "#workflow.add_edge(\"reflect\", \"router\")\n",
    "\n",
    "# QA 노드는 사용자 답변을 기다리기 위해 라우팅 없이 바로 종료\n",
    "workflow.add_edge(\"qa\", END)\n",
    "# reflect 노드도 최종 답변 후 종료\n",
    "workflow.add_edge(\"reflect\", END)\n",
    "\n",
    "memory = InMemorySaver()\n",
    "app = workflow.compile(checkpointer=memory)\n",
    "print(\"\\n✅ Central Router Agent compiled successfully!\")\n",
    "\n",
    "try:\n",
    "    image_bytes = app.get_graph().draw_png()\n",
    "    display(Image(data=image_bytes))\n",
    "except Exception as e:\n",
    "    print(f\"Could not generate graph image: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "1218d4b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🤖 Agent: 안녕하세요! 무엇을 도와드릴까요? (대화를 종료하려면 'quit'을 입력하세요)\n",
      "\n",
      "--------------------\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "\n",
      "[LLM Check] 🤖 Is the conversation ambiguous?\n",
      "--- Conversation ---\n",
      "User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "--------------------\n",
      "Decision: Ambiguous = True (Reason: The user's request is too broad.  While the user specifies 'computer science 3rd year', it lacks specifics on what kind of tasks they need help with (e.g., academic projects, career preparation, skill development, etc.).  The request needs more information to be actionable.)\n",
      "\n",
      "--- Node: ❓ QA Specialist ---\n",
      "\n",
      "[Tool Call] ❓ generate_clarifying_question_tool: 'User: 컴퓨터공학 3학년이 해야할일들을 알려줘'\n",
      "🤖 Agent: (generate_clarifying_question_tool 단계를 처리하고 있습니다...)\n",
      "🤖 Agent: 요청을 명확하게 하기 위해 몇 가지 질문에 답해주세요.\n",
      "\n",
      "❓ What specific area within computer science are you most interested in focusing on?\n",
      "   1. Software Engineering\n",
      "   2. Data Science\n",
      "   3. Artificial Intelligence\n",
      "   4. Networking\n",
      "   5. Cybersecurity\n",
      "\n",
      "❓ What is your current academic standing (GPA, relevant coursework completed)?\n",
      "   1. Above 3.5 GPA, completed core CS courses\n",
      "   2. Between 3.0 and 3.5 GPA, completed most core CS courses\n",
      "   3. Below 3.0 GPA, need to catch up on core CS courses\n",
      "   4. Other\n",
      "\n",
      "❓ What are your career goals after graduation?\n",
      "   1. Software Developer\n",
      "   2. Data Scientist\n",
      "   3. Research Scientist\n",
      "   4. Network Engineer\n",
      "   5. Cybersecurity Analyst\n",
      "   6. Other\n",
      "\n",
      "❓ How much time per week can you dedicate to extracurricular activities or projects?\n",
      "   1. Less than 5 hours\n",
      "   2. 5-10 hours\n",
      "   3. 10-15 hours\n",
      "   4. More than 15 hours\n",
      "\n",
      "(위 질문에 대한 답변을 다음 User 프롬프트에 입력해주세요.)\n",
      "--------------------\n",
      "\n",
      "--------------------\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "\n",
      "[LLM Check] 🤖 Is the conversation ambiguous?\n",
      "--- Conversation ---\n",
      "User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "--------------------\n",
      "Decision: Ambiguous = True (Reason: The user's request is still ambiguous. While the user has specified their major (Computer Science), year (3rd year), GPA range (3.0-3.5), completed core courses, career goal (Software Developer), and available time (less than 5 hours),  it lacks specifics on what kind of 'things to do' they are looking for.  Are they looking for academic tasks, extracurricular activities, project ideas, job search strategies, skill development plans, or something else?  The request needs further clarification to be actionable.)\n",
      "\n",
      "--- Node: ❓ QA Specialist ---\n",
      "\n",
      "[Tool Call] ❓ generate_clarifying_question_tool: 'User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours'\n",
      "🤖 Agent: (generate_clarifying_question_tool 단계를 처리하고 있습니다...)\n",
      "🤖 Agent: 요청을 명확하게 하기 위해 몇 가지 질문에 답해주세요.\n",
      "\n",
      "❓ What specific areas within Computer Science are you interested in focusing on?\n",
      "   1. Web Development\n",
      "   2. Data Science\n",
      "   3. Artificial Intelligence\n",
      "   4. Game Development\n",
      "   5. Networking\n",
      "\n",
      "❓ What is your desired outcome from these activities (e.g., improve skills, build portfolio, gain experience)?\n",
      "   1. Skill Improvement\n",
      "   2. Portfolio Building\n",
      "   3. Experience Gaining\n",
      "   4. Job Application Preparation\n",
      "   5. Research\n",
      "\n",
      "❓ What is your preferred learning style or method?\n",
      "   1. Online Courses\n",
      "   2. Personal Projects\n",
      "   3. Hackathons\n",
      "   4. Internships\n",
      "   5. Workshops\n",
      "\n",
      "❓ Considering your time constraint (less than 5 hours), which of these options is most feasible?\n",
      "   1. Focus on one specific skill\n",
      "   2. Work on a small-scale project\n",
      "   3. Contribute to an open-source project\n",
      "   4. Attend a workshop or online course\n",
      "   5. Network with professionals\n",
      "\n",
      "(위 질문에 대한 답변을 다음 User 프롬프트에 입력해주세요.)\n",
      "--------------------\n",
      "\n",
      "--------------------\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "\n",
      "[LLM Check] 🤖 Is the conversation ambiguous?\n",
      "--- Conversation ---\n",
      "User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "User: Web Develpment, Skill Improvement, Online Courses, Focus on one specific skill\n",
      "--------------------\n",
      "Decision: Ambiguous = True (Reason: While the user has provided some context (Computer Science 3rd year student, software developer, interested in web development skill improvement through online courses), crucial details are missing.  The request lacks specifics on which specific web development skill to focus on, the desired level of proficiency, and what constitutes 'skill improvement'.  A concrete plan for online courses or projects cannot be created without this information.)\n",
      "\n",
      "--- Node: ❓ QA Specialist ---\n",
      "\n",
      "[Tool Call] ❓ generate_clarifying_question_tool: 'User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "User: Web Develpment, Skill Improvement, Online Courses, Focus on one specific skill'\n",
      "🤖 Agent: (generate_clarifying_question_tool 단계를 처리하고 있습니다...)\n",
      "🤖 Agent: 요청을 명확하게 하기 위해 몇 가지 질문에 답해주세요.\n",
      "\n",
      "❓ What specific area of software development are you most interested in improving?\n",
      "   1. Front-end development\n",
      "   2. Back-end development\n",
      "   3. Full-stack development\n",
      "   4. Mobile development\n",
      "   5. Data science\n",
      "\n",
      "❓ What is your preferred learning style for online courses?\n",
      "   1. Video lectures\n",
      "   2. Interactive exercises\n",
      "   3. Reading materials\n",
      "   4. Project-based learning\n",
      "   5. Combination of methods\n",
      "\n",
      "❓ What is your preferred time commitment for online courses per week?\n",
      "   1. Less than 5 hours\n",
      "   2. 5-10 hours\n",
      "   3. 10-15 hours\n",
      "   4. More than 15 hours\n",
      "\n",
      "❓ Which specific skill within web development do you want to focus on?\n",
      "   1. JavaScript frameworks (React, Angular, Vue)\n",
      "   2. Database management (SQL, NoSQL)\n",
      "   3. API development and integration\n",
      "   4. Web security\n",
      "   5. UI/UX design\n",
      "\n",
      "(위 질문에 대한 답변을 다음 User 프롬프트에 입력해주세요.)\n",
      "--------------------\n",
      "\n",
      "--------------------\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "\n",
      "[LLM Check] 🤖 Is the conversation ambiguous?\n",
      "--- Conversation ---\n",
      "User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "User: Web Develpment, Skill Improvement, Online Courses, Focus on one specific skill\n",
      "User: Front-end develpment, Video lectures, Less than 5 hours, Web security\n",
      "--------------------\n",
      "Decision: Ambiguous = False (Reason: The user has specified their field (Computer Science, Software Engineering), their skill gap (3.0-3.5 GPA), their career goal (Software Developer), their time constraint (less than 5 hours), their chosen area for skill improvement (Web Development, specifically Front-end development), preferred learning style (video lectures), and a specific area of interest within Front-end development (Web Security).  This level of detail is sufficient to create a concrete plan for their next steps.)\n",
      "\n",
      "[LLM Check] 🎯 Classifying intent for: 'User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "User: Web Develpment, Skill Improvement, Online Courses, Focus on one specific skill\n",
      "User: Front-end develpment, Video lectures, Less than 5 hours, Web security'\n",
      "Decision: Intent = report\n",
      "\n",
      "--- Node: 📝 Planning Specialist ---\n",
      "\n",
      "[Tool Call] 📝 create_plan_tool (Advanced): 'Front-end develpment, Video lectures, Less than 5 hours, Web security'\n",
      "🤖 Agent: (create_plan_tool 단계를 처리하고 있습니다...)\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "🤖 Agent: (create_plan_tool 단계를 처리하고 있습니다...)\n",
      "\n",
      "--- Node: 🔍 Research Specialist ---\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Research online platforms offering video lectures on front-end development (e.g., Udemy, Coursera, YouTube).'\n",
      "Decision: Optimized query = '프론트엔드 개발 온라인 강의'\n",
      "🔍 Executing search for: '프론트엔드 개발 온라인 강의' (from step: 'Identify relevant front-end development video lecture platforms)'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '프론트엔드 개발 온라인 강의'\n",
      "🔍 Tavily API Raw Response: {'query': '프론트엔드 개발 온라인 강의', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://www.udemy.com/ko/topic/front-end-web-development/?srsltid=AfmBOoovVtup75tu-grYsAnrEN74tqTWzJcRmAK1JTHpbXVccxJvTOts', 'title': '프론트 엔드 웹 개발 강의 | 온라인으로 배워보세요 - Udemy', 'content': '프런트엔드 웹 개발 강의에서는 HTML, CSS, JavaScript로 웹사이트 인터페이스를 만드는 데 중점을 둡니다. 반응형 디자인, DOM 조작 및 프레임워크 통합 스킬은 동적', 'score': 0.83290404, 'raw_content': None}, {'url': 'https://www.udemy.com/ko/topic/front-end-web-development/?srsltid=AfmBOoqeB55HxveXf9mWDT0xi3_okQItKnstTRc-rg9Pg-i-jsvguSuK', 'title': '프론트 엔드 웹 개발 강의 | 온라인으로 배워보세요 - Udemy', 'content': '프런트엔드 웹 개발 강의에서는 HTML, CSS, JavaScript로 웹사이트 인터페이스를 만드는 데 중점을 둡니다. 반응형 디자인, DOM 조작 및 프레임워크 통합 스킬은 동적', 'score': 0.83290404, 'raw_content': None}, {'url': 'https://www.inflearn.com/tag-curation/common_tag/curation-frontend-20220509?srsltid=AfmBOopQm8cKbwSUTU3F42uGRd4DCjnHGIhaX7XahvbvHJkvqWAKl3kt', 'title': '프론트엔드 Best 강의 - 인프런 | 학습하기', 'content': \"#### 프론트엔드 개발을 위한 모든 강의 인프런에 '다' 있어요 💡\\n\\n프로그래밍 언어와 프레임워크까지,  \\n배울 것도, 알아야 되는 것도  \\n너~무 많은 프론트엔드!\\n\\n어떤 공부를 해야 하는지  \\n고민이 있진 않나요?\\n\\n프론트엔드 개발이 처음인 입문자 강의부터  \\n레벨업이 필요한 FE 개발자용 강의까지,  \\n여러분에게 딱 맞는  \\n프론트엔드 BEST 강의를 만나보세요.\\n\\n#### 이미 많은 분들이 인프런과 함께하고 있어요.\\n\\n#### 나에게 필요한 프론트엔드 스택은? ✔️ Click ✔️\\n\\n#HTML/CSS #JavaScript #TypeScript\\n\\n#React #Vue #Svelte\\n\\n입문자를 위한 반응형 웹 기초 강의\\n\\n#무료강의 #미디어쿼리 #가변그리드 #실습\\n\\nCSS Flex와 Grid 제대로 익히기\\n\\n#개념+실습 #실무적용가능 #반응형\\n\\n초보자를 위한 HTML 기초\\n\\n#주니어개발자추천 #WHATWG #웹표준\\n\\n[[리뉴얼] 렛츠기릿 자바스크립트]( [...] 트렐로 개발로 배우는 Vuejs, Vuex, Vue-Router 프론트엔드 실전 기술\\n\\n중급이상\\n\\n#### 김정환트렐로 개발로 배우는 Vuejs, Vuex, Vue-Router 프론트엔드 실전 기술\\n\\n### 트렐로 개발로 배우는 Vuejs, Vuex, Vue-Router 프론트엔드 실전 기술\\n\\n자바스크립트 : 기초부터 실전까지 올인원\\n\\n초급\\n\\n#### 코딩알려주는누나자바스크립트 : 기초부터 실전까지 올인원\\n\\n### 자바스크립트 : 기초부터 실전까지 올인원\\n\\n초보자를 위한 HTML 기초\\n\\n초급\\n\\n#### 조은초보자를 위한 HTML 기초\\n\\n### 초보자를 위한 HTML 기초\\n\\nSvelte.js 입문 가이드\\n\\n초급\\n\\n#### HEROPYSvelte.js 입문 가이드\\n\\n### Svelte.js 입문 가이드\\n\\n고객센터\\n\\nGet the app\\n\\n채널톡 아이콘 [...] ### Vue.js 중급 강좌 - 웹앱 제작으로 배워보는 Vue.js, ES6, Vuex\\n\\n함수형 프로그래밍과 JavaScript ES6+\\n\\n초급\\n\\n#### MDU 유인동함수형 프로그래밍과 JavaScript ES6+\\n\\n### 함수형 프로그래밍과 JavaScript ES6+\\n\\n할인 마감 D-2\\n\\n한 입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지\\n\\n초급\\n\\n#### 이정환 Winterlood한 입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지\\n\\n### 한 입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지\\n\\n## 가장 사랑받는 '프론트엔드 Best 강의'\\n\\n## 프론트엔드 Best 강의\\n\\n인프런이 자신 있게 추천하는 FE Best 강의,\\n나에게 맞는 강의를 골라 들어보세요!\\n\\n## 프론트엔드 Best 강의\\n\\n할인 마감 D-2\\n\\n한 입 크기로 잘라 먹는 리액트(React.js) : 기초부터 실전까지\\n\\n초급\", 'score': 0.7785319, 'raw_content': None}], 'response_time': 3.27, 'request_id': '71087be1-bc55-4c82-bf4a-f150f03fb013'}\n",
      "✅ Found 3 results for '프론트엔드 개발 온라인 강의'\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Refine search results from step 1 to include only video lectures with a total duration of less than 5 hours.'\n",
      "Decision: Optimized query = '컴퓨터공학 3학년 프론트엔드 웹 개발 영상 강의 5시간 미만'\n",
      "🔍 Executing search for: '컴퓨터공학 3학년 프론트엔드 웹 개발 영상 강의 5시간 미만' (from step: 'Filter lectures based on duration (under 5 hours))'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '컴퓨터공학 3학년 프론트엔드 웹 개발 영상 강의 5시간 미만'\n",
      "🔍 Tavily API Raw Response: {'query': '컴퓨터공학 3학년 프론트엔드 웹 개발 영상 강의 5시간 미만', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://school.fun-coding.org/course/frontstart', 'title': '탄탄한 프런트엔드 기본 부트캠프 - 잔재미코딩', 'content': \"입문자에서 시작해서, 풀스택이 되기까지 전 과정을 조금씩 난이도를 높여가며, 상세하고, 체계적으로 익힐 수 있도록 강의를 만들고 있습니다. 해당 문법과 지식 이해를 돕기 위해, 간결한 코드와 충분한 설명을 하되, 이해가 필요한 부분은 그때그때 컴퓨터 공학까지 설명드려서, 좋은 개발자가 될 수 있는 기본기를 닦으실 수 있습니다.\\n\\nImage 4\\n\\n본 강의는 전체 풀스택 강의 시리즈 Part2로, 본 강의 안에서는 다음 서비스 개발을 위한 특정 웹페이지를 선택하여 어떤 프레임워크와 라이브러리도 쓰지 않고, 빈 파일부터 시작하여 HTML, CSS, Javascript + ES6 를 사용해서 한땀한땀 코드 완성까지 함께 해봅니다.\\n\\n### '아! 진짜 다르구나!' 라고 느낄 수 있도록\\n\\n고민고민해서 만드는 IT강의 시리즈입니다\\n\\n### IT 를 잘하려면, 체계적으로 익히세요 [...] IT 기술은 연계되어 있고, 기술을 연결하였을 때, 비로소 그럴듯한 서비스나, 데이터 과학 기술이 가능합니다. 연결된 기술 전반을 난이도를 차근차근 올리며, 핵심을 익히시면, 짧은 시간에 효율적으로 깊이있게 익힐 수 있고, 시스템과 데이터 전반이 드디어 이해가 되고, 각 기술에 대한 이해의 깊이도 달라집니다. 이러한 깊이와 눈을 가지면, 비로소 개발자와 데이터 커리어에서 경쟁력을 갖츨 수 있고, 시니어 레벨도 가능합니다.\\n\\n이를 위해 각 분야의 핵심 기술을 짧은 시간에 정리할 수 있는 로드맵을 만들고 있습니다.\\n\\nImage 5\\n\\n### 본 강의가 포함된 로드맵\\n\\n### 모든 강의는 잔재미코딩 Dave Lee 강사 한명이 만든 강의입니다\\n\\n난이도와 학습순서까지 고려한 로드맵입니다연결된 각 IT 기술마다 다른 강사에게 다른 교재, 학습 방식으로 익히실 필요 없습니다\\n\\n오랜 현업 + IT강의 경험, 이미 검증된 Dave Lee 강사 한명에게 체계적으로, 가장 빠르게 익히세요 [...] 프론트엔드 기본은 HTML, CSS, Javascript 입니다. React 를 익히더라도, 프론트엔드 기본이 필요합니다. 탄탄한 프론트엔드 기본기가 핵심입니다. 꼼꼼하게 잘 쌓은 기본기 위에, React 든 Flutter 든 익히면 프론트엔드를 원하는대로 만들 수 있습니다.\\n\\n### 대충 알고는 있는데 정리가 안되는 것 같아요\\n\\nHTML, CSS, Javascript 대충은 쓸 것 같은데, 실제로 써보면 원하는대로 다루기 어렵습니다. 반응형, 호환성, ES6 등 흩어져 있는 수많은 문법과 기술, 특히나 프론트엔드는 한번 잘 정리하지 않고서는 생각보다 어렵습니다.\\n\\n### 본 강의는 HTML, CSS, Javascript, 반응형, 호환성, ES6 등 \\n\\n꼭 알아야 할 흩어진 프론트엔드 기본 기술을 꼼꼼히 다룹니다\\n\\nImage 2\\n### 탄탄하고 실질적인 프런트엔드 기본기를 위해 만들었습니다\\n\\n수없이 많은 문법과 기능들로, 프런트엔드의 출발은 정리라는 키워드부터 시작해야 합니다.\", 'score': 0.5142789, 'raw_content': None}, {'url': 'https://www.youtube.com/watch?v=dNEh9YzJEQw', 'title': '프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 6', 'content': '# 프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 6\\n\\n인강덕후\\n3 likes\\n214 views\\n2 May 2025\\n#프론트엔드개발자 #프론트엔드개발자기초 #프론트엔드개발자강의\\n📌 프론트엔드개발자을 기초부터 실무까지 마스터!\\n📌 초보자도 쉽게 누구든지 배울 수 있는 프론트엔드개발자 강의!\\n📌 알지오 평생교육원은 평생교육바우처사용처로 평생교육바우처카드 사용이 가능!\\n📌 관공서와 단체의 수강이 가능하며, 원격평생교육원 수료증 및 학습진도 발급이 가능합니다. \\n📌 알지오 평생교육원 : \\n\\n📌 프론트엔드개발자 강의 바로가기\\n\\n📌 프론트엔드개발자 강의 몰아보기\\n\\n🙏 구독과 좋아요 꼭 부탁드립니다!!!\\n0 comments', 'score': 0.35367426, 'raw_content': None}, {'url': 'https://www.youtube.com/watch?v=TiUEWw4RRag', 'title': '프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 1', 'content': '# 프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 1\\n\\n인강덕후\\n4 likes\\n186 views\\n7 Apr 2025\\n#프론트엔드개발자 #프론트엔드개발자기초 #프론트엔드개발자강의\\n📌 프론트엔드개발자을 기초부터 실무까지 마스터!\\n📌 초보자도 쉽게 누구든지 배울 수 있는 프론트엔드개발자 강의!\\n📌 알지오 평생교육원은 평생교육바우처사용처로 평생교육바우처카드 사용이 가능!\\n📌 관공서와 단체의 수강이 가능하며, 원격평생교육원 수료증 및 학습진도 발급이 가능합니다. \\n📌 알지오 평생교육원 : \\n\\n📌 프론트엔드개발자 강의 바로가기\\n\\n📌 프론트엔드개발자 강의 몰아보기\\n\\n🙏 구독과 좋아요 꼭 부탁드립니다!!!\\n0 comments', 'score': 0.34767053, 'raw_content': None}], 'response_time': 1.43, 'request_id': '25db2e1a-20ef-42e9-b5a3-88c07c871e79'}\n",
      "✅ Found 3 results for '컴퓨터공학 3학년 프론트엔드 웹 개발 영상 강의 5시간 미만'\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Review lecture descriptions and outlines to determine if they cover web security topics.'\n",
      "Decision: Optimized query = '웹 보안 온라인 강의'\n",
      "🔍 Executing search for: '웹 보안 온라인 강의' (from step: 'Assess lecture content relevance to web security)'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '웹 보안 온라인 강의'\n",
      "🔍 Tavily API Raw Response: {'query': '웹 보안 온라인 강의', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://www.privacy.go.kr/front/contents/cntntsView.do?contsNo=107', 'title': '온라인교육 - 개인정보 포털', 'content': '온라인 교육(개인)\\n온라인 교육(단체)\\n현장교육\\n전문강사 정보\\n\\n#### 자주 이용하는 서비스 바로가기\\n\\n 개인정보보호 지원\\n\\n  + 개인정보  \\n    자가진단\\n 개인정보 신청/신고\\n\\n  + 본인인증\\n    개인정보  \\n    열람등요구\\n  + 본인인증\\n    개인정보  \\n    유출신고\\n 개인정보보호 교육\\n\\n  + 본인인증\\n    온라인 교육  \\n    (국민)\\n  + 본인인증\\n    온라인 교육  \\n    (단체)\\n\\n### 교육\\n\\n 개인정보보호교육\\n 온라인교육\\n 현장교육\\n 개인정보보호 전문강사\\n 개인정보보호 분야 혁신인재양성\\n\\n## 온라인교육\\n\\n### 온라인교육 안내\\n\\n개인정보배움터에서 제공하는 온라인 교육 영상을 수강하는 방법으로, 개인수강과 단체수강으로 구분됩니다.  \\n단체수강의 경우는 단체교육과 콘텐츠 공동활용으로 추가 구분됩니다.\\n\\n### 온라인교육 개인수강 방법\\n\\n개인수강 : 개인정보보호교육 과정을 교육 대상자가 개별로 선택, 신청하여 수강하는 방법 [...] 온·오프라인 개인정보보호  \\n  교육서비스를 제공합니다.\\n\\n  + 개인정보보호교육\\n  + 온라인교육\\n  + 현장교육\\n  + 개인정보보호 전문강사\\n  + 개인정보보호 분야 혁신인재양성\\n 자료\\n\\n  ### 자료\\n\\n  개인정보보호의 다양한  \\n  자료를 제공합니다.\\n\\n  + 통계보기\\n    - 침해 처리 현황\\n    - 분쟁조정 처리현황\\n    - ISMS-P 인증현황\\n  + 자료보기\\n    - 법령자료\\n    - 안내서\\n    - 교육자료\\n    - 정책자료\\n  + 상담사례\\n  + 판례보기\\n  + 개인정보 기술포럼\\n    - 포럼 소개\\n    - 포럼 자료\\n 알림/소통\\n\\n  ### 알림/소통\\n\\n  개인정보 포털의  \\n  소식과 소통을 제공합니다.\\n\\n  + 알림창구\\n    - 공지사항\\n    - 카드뉴스\\n    - 집단공고게시\\n    - 홍보자료\\n    - FAQ\\n  + 소통창구\\n    - 설문조사\\n    - 이벤트\\n    - 내정보 지킴이 캠페인\\n\\n 교육\\n 온라인교육 [...] 개인정보보호란?)\\n  + 개인정보바로알기\\n    - 개인정보의이해\\n    - 개인정보보호법\\n  + 위원회소개\\n    - 개인정보보호위원회\\n    - 개인정보분쟁조정위원회\\n  + 개인정보 수칙\\n    - 일반국민\\n    - 사업자\\n    - 어린이/청소년\\n 개인서비스)\\n  + 서비스 모아보기\\n  + 정보주체 권리행사\\n    - 서비스 소개\\n    - 본인확인 내역조회\\n    - 본인확인 내역이 조회되는 웹사이트에 대한 탈퇴신청 지원 서비스\\n    - 개인정보 열람등요구\\n  + 분쟁조정\\n    - 제도 안내\\n    - 분쟁조정 신청\\n    - 집단분쟁 당사자 추가\\n    - 분쟁조정 사건조회\\n  + 지우개(잊힐 권리)\\n    - 제도 안내\\n    - 지우개(잊힐 권리) 신청\\n  + 침해신고\\n  + 다크웹에 유출된 털린 내정보찾기 서비스\\n 기업·공공 서비스)\\n  + 서비스 모아보기\\n  + 개인정보보호도우미\\n    - 개인정보보호 자가진단\\n    - 개인정보 기술지원', 'score': 0.37779367, 'raw_content': None}, {'url': 'https://sec.keris.or.kr/', 'title': '정보보호교육센터', 'content': '신청기간25.08.18 ~ 25.09.10\\n\\n  교육기간25.09.17 ~ 25.09.17\\n\\n  차시정보\\n  7차시  \\n  (\\n  교원:\\n  7시간\\n  ,\\n  교원 외:\\n  7시간\\n  )\\n\\n  교육대상교원, 교육전문직, 일반직 공무원, 공무직 등\\n\\n  강의만족도\\n\\n  (\\n  0\\n  )\\n\\n  39\\n  /\\n  40\\n  ( 대기\\n  /\\n  15\\n  )\\n\\n  신청하기;)\\n  상세보기;)\\n 관심 아이콘\\n\\n  집합과정\\n\\n  (\\n  0\\n  )\\n\\n  (3권역부산대) 웹 해킹과 대응 - 2기; \"(3권역부산대) 웹 해킹과 대응 - 2기\")\\n\\n  신청기간25.08.19 ~ 25.09.12\\n\\n  교육기간25.09.19 ~ 25.09.19\\n\\n  집합과정\\n\\n  관심 아이콘\\n\\n  (3권역부산대) 웹 해킹과 대응 - 2기; \"(3권역부산대) 웹 해킹과 대응 - 2기\")\\n\\n  신청기간25.08.19 ~ 25.09.12\\n\\n  교육기간25.09.19 ~ 25.09.19 [...] 신청기간25.03.31 ~ 25.11.27\\n\\n  교육기간25.03.31 ~ 25.11.30\\n\\n  원격과정\\n  (상시)\\n\\n  관심 아이콘\\n\\n  4차 산업혁명 시대 모바일·사이버 보안 한번에 이해하기; \"4차 산업혁명 시대 모바일·사이버 보안 한번에 이해하기\")\\n\\n  신청기간25.03.31 ~ 25.11.27\\n\\n  교육기간25.03.31 ~ 25.11.30\\n\\n  차시정보\\n  7차시  \\n  (\\n  교원:\\n  7시간\\n  ,\\n  교원 외:\\n  2시간\\n  36분\\n  )\\n\\n  교육대상교원, 교육전문직, 일반직 공무원, 공무직 등\\n\\n  강의만족도\\n\\n  (\\n  132\\n  )\\n\\n  1,267\\n  /\\n  4,000\\n\\n  신청하기;)\\n  상세보기;)\\n 관심 아이콘\\n\\n  원격과정\\n  (상시)\\n\\n  (\\n  133\\n  )\\n\\n  교육 업무환경에서의 안전한 무선랜 환경 이용하기; \"교육 업무환경에서의 안전한 무선랜 환경 이용하기\")\\n\\n  신청기간25.03.31 ~ 25.11.27 [...] 교육기관 개인정보보호 책임자(CPO); \"교육기관 개인정보보호 책임자(CPO)\")\\n\\n  신청기간25.03.31 ~ 25.11.27\\n\\n  교육기간25.03.31 ~ 25.11.30\\n\\n  원격과정\\n  (상시)\\n\\n  관심 아이콘\\n\\n  교육기관 개인정보보호 책임자(CPO); \"교육기관 개인정보보호 책임자(CPO)\")\\n\\n  신청기간25.03.31 ~ 25.11.27\\n\\n  교육기간25.03.31 ~ 25.11.30\\n\\n  차시정보\\n  4차시  \\n  (\\n  교원:\\n  4시간\\n  ,\\n  교원 외:\\n  2시간\\n  03분\\n  )\\n\\n  교육대상교원, 교육전문직, 일반직 공무원, 공무직 등\\n\\n  강의만족도\\n\\n  (\\n  238\\n  )\\n\\n  3,166\\n  /\\n  6,000\\n\\n  신청하기;)\\n  상세보기;)\\n 관심 아이콘\\n\\n  원격과정\\n  (상시)\\n\\n  (\\n  132\\n  )\\n\\n  4차 산업혁명 시대 모바일·사이버 보안 한번에 이해하기; \"4차 산업혁명 시대 모바일·사이버 보안 한번에 이해하기\")', 'score': 0.3534064, 'raw_content': None}, {'url': 'https://academy.kisa.or.kr/cont/programInfo/eduIntroAI.do', 'title': 'AI 보안관제 - KISA 아카데미 - 한국인터넷진흥원', 'content': '- 개인정보처리시스템에 접속한 기록(웹 로그, 요약정보 등)을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 관리하고 있습니다.\\n ⑤ 개인정보의 암호화  \\n  - 이용자의 개인정보는 암호화 되어 저장 및 관리되고 있습니다. 또한 중요한 데이터는 저장 및 전송 시 암호화하여 사용하는 등의 별도 보안기능을 사용하고 있습니다.\\n ⑥ 해킹 등에 대비한 기술적 대책  \\n  - 해킹이나 컴퓨터 바이러스 등에 의한 개인정보 유출 및 훼손을 막기 위하여 보안프로그램을 설치하고 주기적인 갱신·점검을 하며 외부로부터 접근이 통제된 구역에 시스템을 설치하고 기술적, 물리적으로 감시 및 차단하고 있습니다.\\n ⑦ 비인가자에 대한 출입 통제  \\n  - 개인정보를 보관하고 있는 개인정보시스템의 물리적 보관 장소를 별도로 두고 이에 대해 출입통제 절차를 수립, 운영하고 있습니다. [...] | 1. 개인정보의 처리 목적, 수집 항목, 보유 및 이용기간 | 2. 개인정보의 제3자 제공 |\\n| 3. 개인정보 처리의 위탁 | 4. 개인정보의 파기절차 및 방법 |\\n| 5. 정보주체와 법정대리인의 권리·의무 및 행사방법에 관한 사항 | 6. 개인정보의 안전성 확보조치에 관한 사항 |\\n| 7. 개인정보를 자동으로 수집하는 장치의 설치·운영 및 그 거부에 관한 사항 | 8. 개인정보보호 및 고충처리 담당자 |\\n| 9. 정보주체의 권익침해에 대한 구제방법 | 10. 개인정보 관리수준 진단 결과 |\\n| 11. 개인정보파일 등록 현황 | 12. 개인정보 처리방침의 변경에 관한 사항 |\\n\\n#### 개인정보의 처리 목적, 수집 항목, 보유 및 이용기간', 'score': 0.2753189, 'raw_content': None}], 'response_time': 1.47, 'request_id': 'a0317f3a-3061-442c-9d53-c8a7d3d8d820'}\n",
      "✅ Found 3 results for '웹 보안 온라인 강의'\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Check instructor credentials and student reviews to gauge the quality and reliability of the lectures.'\n",
      "Decision: Optimized query = '컴퓨터공학 웹개발 온라인 강의 후기'\n",
      "🔍 Executing search for: '컴퓨터공학 웹개발 온라인 강의 후기' (from step: 'Evaluate instructor credibility and student reviews)'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '컴퓨터공학 웹개발 온라인 강의 후기'\n",
      "🔍 Tavily API Raw Response: {'query': '컴퓨터공학 웹개발 온라인 강의 후기', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://www.udemy.com/ko/courses/development/?srsltid=AfmBOorqT5PzXx_ET41GG0Ea6qk7wMhfWkiOSZuP0dPmilcBtM6e0Kii', 'title': '온라인 웹 개발 및 프로그래밍 강의 - Udemy', 'content': '웹 개발의 처음부터 끝까지 100일 안에 배워봅시다! \"기본\"에서 \"고급\"까지 모든 내용이 포함되어 있습니다!평점: 5점 만점 중 4.7점후기 1175개총 79.5시간651개의 강의', 'score': 0.7348247, 'raw_content': None}, {'url': 'https://coding-groot.tistory.com/93', 'title': '나의 온라인 컴퓨터공학 공부 - Coding Groot - 티스토리', 'content': '저는 사실 FreeCodeCamp의 커리큘럼을 참고하기보단 FreeCodeCamp의 유튜브 채널에서 필요한 주제를 골라서 듣습니다. 과목 당 4시간 이상의 강의 또는 2개 강의로 쪼개서 아주 긴 영상으로 되어있습니다. 이게 처음에는 영상 길이에 압도되고 매번 어디까지 봤는지 기록해야 할 것 같지만 유튜브 영상이라서 다시 접속하면 보던 부분부터 재생되기 때문에 생각보다 불편하진 않았습니다. 그리고 HTML, CSS, JS부터 최근 핫한 Next.js까지 웹 개발과 관련된 강의도 많이 합니다.\\n\\n#### 2. 뭐가 제일 좋은 강의지? 어떤 책이 제일 유명하지?\\n\\n지금 인터넷에 컴퓨터공학 관련 자료들도 넘칩니다. 그래서 어떤 책을 봐야 하는지 결정하는 것도 큰 고민입니다(나름 행복한 고민입니당). 그러다가 찾은 사이트입니다.\\n\\n> Which subjects should you learn, and why?   \\n>  👉 내가 어떤 과목을 들어야 하고 왜 들어야 하는가? [...] 가성비 넘치는 강의들이 많은 곳입니다.\\n 할인 이벤트도 자주해서 부담이 된다면 기념일을 기다려보세용.\\n 수학, 소프트웨어 개발, 그래픽 등의 다양한 분야 강의들이 있습니다.\\n 유료이지만 다른 사이트의 유료 강의에 비해서 저렴했고 유튜브보단 더 전문적인(실무에 가까운) 강의들이 많습니다. 리뷰도 많이 달리고 무료로 기본적인 강의는 많이있습니다.\\n 유튜브의 랜덤한 강의보다 체계적이라서 마음 놓고 학습하기 좋았습니다. 강의마다 다르겠지만 후기 참고하셔서 구매하시면 돈값은 무조건했습니닷!\\n 최근에 관심있는 강의가 생겨서 구매해서 며칠 동안 수강했는데 쾌적하게 볼 수 있었습니다!!\\n\\n코딩 도장\\n\\n C언어, 파이썬, 자료구조, 알고리즘을 학습하기 좋은 곳입니다.\\n C언어를 까먹을 때마다 들어가서 복습하는 사이트입니다ㅎㅎ.\\n 주제별로 동영상도 있고 코드가 첨부되어 있어서 학습하기 편합니다.\\n\\nC# Study [...] 국내에서 운영하는 무료 강의 사이트들입니다. 생활코딩, 인프런, 코딩 도장, 위키 독스, ... 이 모든 사이트를 모아서 정리한 사이트가 있습니다. 첫 번째 링크만 저장해두면 나중에 찾기 편할 것 같습니다. 사이트에 Edwith의 링크는 들어가 있지 않아서 따로 추가했습니다.\\n\\n[국내 사이트]\\n\\n 가볍게 듣기 좋습니다.\\n  + 코딩을 잘하고 싶은 사람들(전공자 기준 아님!)을 위한 강의를 하는 곳입니다.\\n 빠르고 쉽게 기초적인 내용을 배울 수 있습니다.\\n 방대한 Web의 세상에서 도대체 뭐부터 시작해야 할지 몰랐었을 때 큰 도움을 받았습니다.\\n 아무것도 모르는 신입생 때 여기에 있는 이고잉님의 Web(HTML/CSS/JS) 강의를 일주일에 한 챕터 단위로 돌파하는 스터디를 한 후부터 웹으로 입문했습니다.', 'score': 0.6633424, 'raw_content': None}, {'url': 'https://notavoid.tistory.com/211', 'title': '개발자에게 유용한 온라인 강의 플랫폼 비교: Udemy vs Coursera vs ...', 'content': 'edX 추천 개발 과정. 무료 프로그래밍 교육을 원한다면 다음 과정들을 추천합니다: MIT Introduction to Computer Science: Python을 이용한 컴퓨터 과학', 'score': 0.25275317, 'raw_content': None}], 'response_time': 3.32, 'request_id': '943fca38-3dbb-4760-a94f-452fc8a5f95c'}\n",
      "✅ Found 3 results for '컴퓨터공학 웹개발 온라인 강의 후기'\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Create a comparison table summarizing the key features, content, and reviews of the shortlisted lectures.'\n",
      "Decision: Optimized query = '컴퓨터공학 3학년 웹 프론트엔드 온라인 강좌 비교'\n",
      "🔍 Executing search for: '컴퓨터공학 3학년 웹 프론트엔드 온라인 강좌 비교' (from step: 'Compare identified lectures based on content and reviews)'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '컴퓨터공학 3학년 웹 프론트엔드 온라인 강좌 비교'\n",
      "🔍 Tavily API Raw Response: {'query': '컴퓨터공학 3학년 웹 프론트엔드 온라인 강좌 비교', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://www.udemy.com/ko/topic/front-end-web-development/?srsltid=AfmBOorxwDXAFLC4Axm3l0gZZv6_zONOedwB9l-2F5W5qKHwSMNyTY9H', 'title': '프론트 엔드 웹 개발 강의 | 온라인으로 배워보세요 - Udemy', 'content': '프런트엔드 웹 개발 강의에서는 HTML, CSS, JavaScript로 웹사이트 인터페이스를 만드는 데 중점을 둡니다. 반응형 디자인, DOM 조작 및 프레임워크 통합 스킬은 동적', 'score': 0.45784017, 'raw_content': None}, {'url': 'https://hereiam68.tistory.com/5', 'title': '비전공자의 CS전공과목 독학하기 (feat. 서울대 컴퓨터공학 커리큘럼)', 'content': \"> 1학년 : 이산수학\\n> \\n> 2학년 : 전기전자회로, 컴퓨터구조, 컴퓨터프로그래밍, 논리설계, 자료구조\\n> \\n> 3학년 : 알고리즘, 시스템프로그래밍\\n\\n각 과목별 학습 목표는 다음과 같다.\\n\\n1.   이산수학: 컴퓨터공학과 밀접하게 관련된 수학적 내용들에 대하여 배우고 이러한 수학적 개념들이 컴퓨터공학에서 어떻게 쓰이는지에 대해서 살펴봄\\n\\n2.   전기전자회로: 회로 분석 방법, 논리 회로와 증폭회로의 원리, 전자회로의 핵심 소자인 MOS와 Bipolar 트랜지스터의 특성, 디지털 하드웨어의 전기적인 특성, 속도와 에너지 소모에 대한 기초지식 습득\\n\\n3.   컴퓨터구조: 컴퓨터를 구성하는 주요 구성 요소들의 기능과 그들 상호간의 작용을 이해하고 이를 바탕으로 컴퓨터 시스템을 구현하는데 사용되는 여러 설계 기법, 컴퓨터 발전의 역사적 고찰 및 컴퓨터 시스템의 성능 분석에 필요한 지식 학습\\n\\n4.   컴퓨터프로그래밍: Java와 C++언어를 이용한 객체지향 프로그래밍 학습 [...] > 1학년 : 프로그래밍연습\\n> \\n> 2학년 : 프로그래밍의 원리\\n> \\n> 3학년 : 오토마타 이론, 운영체제, 하드웨어시스템설계, 프로그래밍언어, 선형 및 비선형 계산모델, 디지털신호처리, 데이터마이닝개론, 데이터베이스, 데이터통신, IT창업개론\\n> \\n> 4학년 : 임베디드시스템과 응용, 소프트웨어공학, 소프트웨어응용, 모바일 컴퓨팅과 응용, 인공지능, 컴파일러, 컴퓨터그래픽스, 컴퓨터네트워크, 컴퓨터모델링, 멀티코어 컴퓨팅, 컴퓨터보안, 웹정보시스템, 컴퓨터융합응용, 인간컴퓨터상호작용, 소셜네트워크 분석, 기계학습 개론, 컴퓨터비전, 컴퓨터신기술특강, 인터넷보안, 양자컴퓨팅 및 정보의 기초, 블록체인의 이해, 딥러닝의 기초\\n\\n앞으로의 계획 [...] > MIT OCW ocw.mit.edu/index.htm\\n> \\n> UDEMYwww.udemy.com/ko/\\n> \\n> KOCWwww.kocw.net/home/index.do\\n> \\n> COURSERA www.coursera.org\\n> \\n> EDXwww.edx.org/\\n> \\n> UDACITYwww.udacity.com/\\n> \\n> khan academyko.khanacademy.org/\\n\\n앞으로 블로그에서 내가 컴퓨터공학 전공과목을 학습한 내용을 정리하고 이를 위해 참고한 자료들도 함께 공유할 예정이다. 이 내용이 CS 전공 과목을 독학하고자 하는 다른 사람들에게도 도움이 되길 바란다.\\n\\n공유하기\\n\\nURL 복사 카카오톡 공유 페이스북 공유 엑스 공유\\n\\n게시글 관리\\n\\n_구독하기_진부리 개발로그\\n\\n#### '비전공자 개발공부' 카테고리의 다른 글\\n\\n| 프론트엔드&백엔드&DevOps 개발자 로드맵(0) | 2021.02.25 |\", 'score': 0.31113425, 'raw_content': None}, {'url': 'https://www.reddit.com/r/webdev/comments/16x3u10/i_want_to_study_web_dev_but_only_know_computer/?tl=ko', 'title': '웹 개발 공부하고 싶은데, 컴퓨터 공학 프로그래밍만 알아 ㅠㅠ - Reddit', 'content': '시작하려면 프론트엔드나 백엔드 중 하나에 집중하고 거기서부터 성장해봐. ... 코딩이나 프로그래밍에 대한 사전 지식 없이 컴퓨터 과학 과정을 듣고', 'score': 0.18532747, 'raw_content': None}], 'response_time': 3.09, 'request_id': 'd1210f93-280e-40a6-9790-e3c30d244abc'}\n",
      "✅ Found 3 results for '컴퓨터공학 3학년 웹 프론트엔드 온라인 강좌 비교'\n",
      "\n",
      "[LLM Check] ➡️ Optimizing search query: 'Based on the comparison, choose the video lecture(s) that best meet the requirements.'\n",
      "Decision: Optimized query = '컴퓨터공학 3학년 프론트엔드 웹 개발 온라인 강의 추천'\n",
      "🔍 Executing search for: '컴퓨터공학 3학년 프론트엔드 웹 개발 온라인 강의 추천' (from step: 'Select the most suitable lecture(s))'\n",
      "\n",
      "[Tool Call] 🔍 web_search_tool: '컴퓨터공학 3학년 프론트엔드 웹 개발 온라인 강의 추천'\n",
      "🔍 Tavily API Raw Response: {'query': '컴퓨터공학 3학년 프론트엔드 웹 개발 온라인 강의 추천', 'follow_up_questions': None, 'answer': None, 'images': [], 'results': [{'url': 'https://school.fun-coding.org/course/frontstart', 'title': '탄탄한 프런트엔드 기본 부트캠프 - 잔재미코딩', 'content': '프런트엔드 기술만 빨리 정리하고 싶으시다면, 본 강의만을 수강하셔도 좋습니다. 다만, 프로그래밍을 한번도 다뤄보지 않은 완전 입문자시라면, 파이썬입문과 크롤링 부트캠프 강의와 함께 풀스택 강의를 로드맵을 통해, 차근차근 익혀보시기를 추천드립니다. 보다 차근차근 필요한 역량을 쌓으실 수 있습니다.\\n\\n### 입문자도 이해할 수 있도록\\n\\n간결하면서도, 꼼꼼히 작성된 자료를 기반으로,\\n\\n강의 중, 각자 테스트도 해볼 수 있도록\\n\\n기능별 샘플코드와 테스트까지 바로 하실 수 있습니다\\n\\nImage 3\\n\\n   각 기능별 샘플코드를 프로젝트로 작성하여 제공해드리며, 실전 웹페이지 코드파일을 제공해드립니다.\\n   강의 자료는 온라인에서 언제든 확인하실 수 있도록 제공해드립니다. (단, 복사 및 다운로드는 저작권 이슈로 제한하였습니다.)\\n\\n### 체계적으로 익힐 수 있을까요? [...] 트랜드를 반영하여 수시로 업데이트하고 있습니다\\n\\n개선점은 질의응답란에 남겨주시면 신속히 반영하겠습니다\\n\\n### 네카라쿠배도 사내 강의로 선택하는 공식 강의!\\n\\n입문자를 위한 프런트엔드 웹기술 기본기를 다져줄\\n\\n완성도 높은 강의 시리즈 (풀스택 Part2)\\n\\n본 강의는 풀스택 강의 시리즈 Part2 강의로 파이썬 백엔드(Part1) 강의에 이어서, 풀스택을 위한 탄탄한 프론트엔드 기본을 익히는 강의입니다. 상용화도 가능한 웹서비스 개발을 위한 HTML5, CSS, Javascript (VanillaJS, 바닐라 자바스크립트) + ES6 을 상세히 정리하고 익히는 강의입니다.\\n\\n### 프론트엔드 기본기를 제대로 쌓고자 한다면? [...] 프론트엔드 기본은 HTML, CSS, Javascript 입니다. React 를 익히더라도, 프론트엔드 기본이 필요합니다. 탄탄한 프론트엔드 기본기가 핵심입니다. 꼼꼼하게 잘 쌓은 기본기 위에, React 든 Flutter 든 익히면 프론트엔드를 원하는대로 만들 수 있습니다.\\n\\n### 대충 알고는 있는데 정리가 안되는 것 같아요\\n\\nHTML, CSS, Javascript 대충은 쓸 것 같은데, 실제로 써보면 원하는대로 다루기 어렵습니다. 반응형, 호환성, ES6 등 흩어져 있는 수많은 문법과 기술, 특히나 프론트엔드는 한번 잘 정리하지 않고서는 생각보다 어렵습니다.\\n\\n### 본 강의는 HTML, CSS, Javascript, 반응형, 호환성, ES6 등 \\n\\n꼭 알아야 할 흩어진 프론트엔드 기본 기술을 꼼꼼히 다룹니다\\n\\nImage 2\\n### 탄탄하고 실질적인 프런트엔드 기본기를 위해 만들었습니다\\n\\n수없이 많은 문법과 기능들로, 프런트엔드의 출발은 정리라는 키워드부터 시작해야 합니다.', 'score': 0.7760977, 'raw_content': None}, {'url': 'https://www.udemy.com/ko/topic/front-end-web-development/?srsltid=AfmBOoros8OSpYT-Wg-IBTME1pLeyujFMENdQBAehoiyGdPZ0vmg5iKr', 'title': '프론트 엔드 웹 개발 강의 | 온라인으로 배워보세요 - Udemy', 'content': '프런트엔드 웹 개발 강의에서는 HTML, CSS, JavaScript로 웹사이트 인터페이스를 만드는 데 중점을 둡니다. 반응형 디자인, DOM 조작 및 프레임워크 통합 스킬은 동적', 'score': 0.7668008, 'raw_content': None}, {'url': 'https://blog.naver.com/hann726/222086272496?viewType=pc', 'title': '비전공자를 위한 코딩 인강 사이트 모음(무료, 유료) : 네이버 블로그', 'content': '1. 생활코딩 · 2. 구름EDU · 3. 네이버 부스트코스 · 1. 코드잇 · 2. 인프런 · 3. 노마드 코더.', 'score': 0.21084791, 'raw_content': None}], 'response_time': 4.18, 'request_id': '75c0f43e-9e8a-4c63-b64e-8c63e3399f9a'}\n",
      "✅ Found 3 results for '컴퓨터공학 3학년 프론트엔드 웹 개발 온라인 강의 추천'\n",
      "🤖 Agent: (web_search_tool 단계를 처리하고 있습니다...)\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "🤖 Agent: (web_search_tool 단계를 처리하고 있습니다...)\n",
      "\n",
      "--- Node: ✍️ Generation Specialist ---\n",
      "\n",
      "--- Node: 🧑‍💼 Central Router (PM) ---\n",
      "\n",
      "--- Node: 🤔 Reflection Specialist ---\n",
      "\n",
      "[Tool Call] 🤔 reflect_and_critique_tool...\n",
      "--- 비평 생성용 LLM 프롬프트 ---\n",
      "\n",
      "    ... (기존 시스템 프롬프트 내용) ...\n",
      "    \n",
      "\n",
      "Conversation History:\n",
      "\"User: 컴퓨터공학 3학년이 해야할일들을 알려줘\n",
      "User: Software Engineering, Between 3.0 and 3.5 GAP, completed most core CS courses, Software Develper, Less than 5 hours\n",
      "User: Web Develpment, Skill Improvement, Online Courses, Focus on one specific skill\n",
      "User: Front-end develpment, Video lectures, Less than 5 hours, Web security\n",
      "Assistant: ## 컴퓨터공학 3학년 프론트엔드 웹 개발 학습 계획 (5시간 미만, 주 1회)\n",
      "\n",
      "**목표:**  프론트엔드 웹 개발 기초 다지기 (HTML, CSS, JavaScript) 및 웹 보안 기초 학습\n",
      "\n",
      "**기간:**  8주 (상황에 따라 조정 가능)\n",
      "\n",
      "**학습 플랫폼:** Udemy, Inflearn, 잔재미코딩 (선택)  YouTube (보조자료)\n",
      "\n",
      "**참고:** 본 계획은 제한된 시간(주 5시간 미만) 내에서 효율적인 학습을 목표로 합니다. 각 주차별 학습량은  자신의 학습 속도에 따라 조절해야 합니다.  \n",
      "\n",
      "\n",
      "**1주차: HTML 기초**\n",
      "\n",
      "* **목표:** HTML 기본 문법, 웹 페이지 구조 이해,  기본 태그 활용\n",
      "* **학습 자료:**\n",
      "    * Inflearn: \"초보자를 위한 HTML 기초\" 강의 (수강 시간 확인 후 선택)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 HTML 관련 부분 (무료 강의 및 체험 강의 활용)\n",
      "    * YouTube:  \"프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 1\" (보조 자료)\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:**  간단한 웹 페이지 제작 연습 (예: 개인 포트폴리오 페이지의 기본 구조 만들기)\n",
      "\n",
      "\n",
      "**2주차: CSS 기초**\n",
      "\n",
      "* **목표:** CSS 기본 문법, 스타일 적용 방법, 선택자 이해, 박스 모델 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn:  CSS 관련 강의 (Flex와 Grid 강의 우선 고려)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 CSS 관련 부분\n",
      "    * 잔재미코딩: \"탄탄한 프런트엔드 기본 부트캠프\" 강의 (CSS 부분, 유료 강의이므로 무료 강의와 비교 후 결정)\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:** 1주차에 제작한 웹 페이지에 CSS 적용하여 스타일링 연습\n",
      "\n",
      "\n",
      "**3주차: JavaScript 기초**\n",
      "\n",
      "* **목표:** JavaScript 기본 문법, 변수, 데이터 타입, 제어문, 함수 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn: \"자바스크립트 : 기초부터 실전까지 올인원\" 강의 (수강 시간 확인 후 선택)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 JavaScript 관련 부분\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:**  간단한 JavaScript 스크립트 작성 연습 (예: 버튼 클릭 시 내용 변경, 간단한 계산기)\n",
      "\n",
      "\n",
      "**4주차: JavaScript 심화 (DOM 조작)**\n",
      "\n",
      "* **목표:** DOM (Document Object Model) 이해, DOM 조작을 이용한 동적 웹 페이지 구현\n",
      "* **학습 자료:**\n",
      "    * Udemy, Inflearn: JavaScript 심화 강의 (DOM 조작 관련 부분)\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:** 2, 3주차 웹 페이지에 JavaScript를 활용하여 동적 요소 추가 (예: 목록 추가, 내용 변경)\n",
      "\n",
      "\n",
      "**5주차: 반응형 웹 디자인**\n",
      "\n",
      "* **목표:** 반응형 웹 디자인 개념 이해, 미디어 쿼리 활용\n",
      "* **학습 자료:**\n",
      "    * Inflearn: 반응형 웹 기초 강의\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 반응형 디자인 관련 부분\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:**  기존 웹 페이지를 반응형으로 수정\n",
      "\n",
      "\n",
      "**6주차: 웹 보안 기초**\n",
      "\n",
      "* **목표:**  웹 보안의 기본 개념, XSS, CSRF 등 주요 공격 방식 이해, 기본적인 방어 기법 숙지\n",
      "* **학습 자료:**\n",
      "    *  KISA 아카데미 또는 정보보호교육센터의 관련 자료 (무료 강의 및 자료 활용)\n",
      "    *  Udemy, Inflearn: 웹 보안 관련 강의 (시간 제약으로 선택적으로 수강)\n",
      "* **학습 시간:** 2시간\n",
      "* **활동:**  웹 보안 관련 자료 정리 및 학습 내용 요약\n",
      "\n",
      "\n",
      "**7주차:  프론트엔드 프레임워크 소개 (React 또는 Vue.js 중 택일)**\n",
      "\n",
      "* **목표:**  React 또는 Vue.js 중 하나의 프레임워크 기본 개념 및 장단점 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn: React 또는 Vue.js 관련 입문 강의 (시간 제약으로 기본적인 개념 학습에 집중)\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:**  간단한 예제 프로젝트 진행 (선택)\n",
      "\n",
      "\n",
      "**8주차: 프로젝트 및 복습**\n",
      "\n",
      "* **목표:**  지금까지 학습한 내용을 바탕으로 간단한 웹 애플리케이션 프로젝트 진행 및 복습\n",
      "* **학습 자료:**  이전 주차 학습 자료 활용\n",
      "* **학습 시간:** 5시간\n",
      "* **활동:**  프로젝트 구현 및 피드백\n",
      "\n",
      "\n",
      "**추가 학습:**\n",
      "\n",
      "*  시간이 허락한다면,  `잔재미코딩`의 \"탄탄한 프런트엔드 기본 부트캠프\" 강의를 수강하는 것을 고려해 볼 수 있습니다.  다만, 유료 강의이며, 전체 강의 시간을 확인 후 시간 계획에 맞춰 수강 여부를 결정해야 합니다.\n",
      "*  웹 개발 관련 뉴스레터 구독을 통해 최신 기술 동향을 파악하는 것도 도움이 됩니다.\n",
      "\n",
      "\n",
      "**중요 사항:** 학습 계획은 참고 자료이며, 개인의 학습 속도와 이해도에 따라 조정해야 합니다.  매주 학습 내용을 정리하고,  실제 프로젝트를 통해  학습 내용을 적용하는 것이 중요합니다.  꾸준한 학습과 실습을 통해 목표 달성을 위한 노력을 지속해야 합니다.\"\n",
      "---------------------------------\n",
      "--- LLM의 원본 비평 응답 ---\n",
      "This is a good starting point for a frontend web development learning plan.  Here are some suggestions to make it even better:\n",
      "\n",
      "**Improvements and Additions:**\n",
      "\n",
      "* **Specificity in Learning Resources:**  Instead of broadly suggesting \"Udemy/Inflearn:  JavaScript 심화 강의 (DOM 조작 관련 부분),\"  provide specific course names or links whenever possible.  This significantly increases the plan's usability.  Many Udemy and Inflearn courses have overlapping content, so recommending specific high-rated courses will improve efficiency.\n",
      "\n",
      "* **Version Control (Git):**  Integrate Git and GitHub (or GitLab, Bitbucket) into the plan.  Version control is crucial for any software developer, and it should be introduced early.  Suggest creating a GitHub repository for each project.\n",
      "\n",
      "* **Project Ideas (More Concrete):** The project suggestions are a bit vague.  Provide more specific project ideas for each week, or at least for the final project.  Examples:\n",
      "\n",
      "    * **Week 1:**  Simple HTML page with a heading, paragraph, image, and link.\n",
      "    * **Week 2:** Style the Week 1 page with CSS, focusing on layout and basic styling.\n",
      "    * **Week 3:** Add JavaScript to display a greeting based on the time of day.\n",
      "    * **Week 8:**  A to-do list app, a simple calculator, or a basic weather app (using an API).\n",
      "\n",
      "* **Debugging and Troubleshooting:** Add a section or mention within each week about debugging techniques.  This is a crucial skill for developers.  Suggest using the browser's developer tools.\n",
      "\n",
      "* **Testing:** Briefly mention the importance of testing and perhaps introduce simple testing concepts as the plan progresses.\n",
      "\n",
      "* **Accessibility:**  Include a section (perhaps in Week 5 or 6) on web accessibility best practices (WCAG).  This is becoming increasingly important.\n",
      "\n",
      "* **Time Tracking:**  Suggest a time-tracking method (app or simple spreadsheet) to monitor progress and identify areas needing more or less time.\n",
      "\n",
      "* **Portfolio Building:** Emphasize the importance of building a portfolio and suggest adding each week's project to it.  GitHub Pages is a great option for hosting a portfolio.\n",
      "\n",
      "* **Community Engagement:**  Encourage joining online communities (e.g., Stack Overflow, Discord servers for frontend development) for asking questions and learning from others.\n",
      "\n",
      "\n",
      "**Revised Week Structure Example (incorporating some suggestions):**\n",
      "\n",
      "**Week 1: HTML Fundamentals & Git Introduction**\n",
      "\n",
      "* **Goal:** Learn basic HTML syntax, create a simple webpage, and set up a Git repository.\n",
      "* **Resources:**\n",
      "    * FreeCodeCamp's Responsive Web Design Certification (HTML sections) - *Specific and well-regarded resource*\n",
      "    * **Git Tutorial:**  [Link to a good Git tutorial, e.g., GitHub's learning lab]\n",
      "* **Project:** Create a simple webpage with a heading, paragraph, image, and link.  Commit changes to your Git repository.\n",
      "\n",
      "**(Repeat similar structure for other weeks, adding more detail and specific resources.)**\n",
      "\n",
      "\n",
      "By adding these details and focusing on concrete actions, the learning plan becomes much more actionable and effective for a student.  Remember to always link to specific resources whenever possible.\n",
      "---------------------------------\n",
      "\n",
      "[생성된 비평 내용]\n",
      "This is a good starting point for a frontend web development learning plan.  Here are some suggestions to make it even better:\n",
      "\n",
      "**Improvements and Additions:**\n",
      "\n",
      "* **Specificity in Learning Resources:**  Instead of broadly suggesting \"Udemy/Inflearn:  JavaScript 심화 강의 (DOM 조작 관련 부분),\"  provide specific course names or links whenever possible.  This significantly increases the plan's usability.  Many Udemy and Inflearn courses have overlapping content, so recommending specific high-rated courses will improve efficiency.\n",
      "\n",
      "* **Version Control (Git):**  Integrate Git and GitHub (or GitLab, Bitbucket) into the plan.  Version control is crucial for any software developer, and it should be introduced early.  Suggest creating a GitHub repository for each project.\n",
      "\n",
      "* **Project Ideas (More Concrete):** The project suggestions are a bit vague.  Provide more specific project ideas for each week, or at least for the final project.  Examples:\n",
      "\n",
      "    * **Week 1:**  Simple HTML page with a heading, paragraph, image, and link.\n",
      "    * **Week 2:** Style the Week 1 page with CSS, focusing on layout and basic styling.\n",
      "    * **Week 3:** Add JavaScript to display a greeting based on the time of day.\n",
      "    * **Week 8:**  A to-do list app, a simple calculator, or a basic weather app (using an API).\n",
      "\n",
      "* **Debugging and Troubleshooting:** Add a section or mention within each week about debugging techniques.  This is a crucial skill for developers.  Suggest using the browser's developer tools.\n",
      "\n",
      "* **Testing:** Briefly mention the importance of testing and perhaps introduce simple testing concepts as the plan progresses.\n",
      "\n",
      "* **Accessibility:**  Include a section (perhaps in Week 5 or 6) on web accessibility best practices (WCAG).  This is becoming increasingly important.\n",
      "\n",
      "* **Time Tracking:**  Suggest a time-tracking method (app or simple spreadsheet) to monitor progress and identify areas needing more or less time.\n",
      "\n",
      "* **Portfolio Building:** Emphasize the importance of building a portfolio and suggest adding each week's project to it.  GitHub Pages is a great option for hosting a portfolio.\n",
      "\n",
      "* **Community Engagement:**  Encourage joining online communities (e.g., Stack Overflow, Discord servers for frontend development) for asking questions and learning from others.\n",
      "\n",
      "\n",
      "**Revised Week Structure Example (incorporating some suggestions):**\n",
      "\n",
      "**Week 1: HTML Fundamentals & Git Introduction**\n",
      "\n",
      "* **Goal:** Learn basic HTML syntax, create a simple webpage, and set up a Git repository.\n",
      "* **Resources:**\n",
      "    * FreeCodeCamp's Responsive Web Design Certification (HTML sections) - *Specific and well-regarded resource*\n",
      "    * **Git Tutorial:**  [Link to a good Git tutorial, e.g., GitHub's learning lab]\n",
      "* **Project:** Create a simple webpage with a heading, paragraph, image, and link.  Commit changes to your Git repository.\n",
      "\n",
      "**(Repeat similar structure for other weeks, adding more detail and specific resources.)**\n",
      "\n",
      "\n",
      "By adding these details and focusing on concrete actions, the learning plan becomes much more actionable and effective for a student.  Remember to always link to specific resources whenever possible.\n",
      "-----------------------------------\n",
      "\n",
      "[최종 답변]\n",
      "🤖 Agent: ## 최종 보고서 초안:\n",
      "## 컴퓨터공학 3학년 프론트엔드 웹 개발 학습 계획 (5시간 미만, 주 1회)\n",
      "\n",
      "**목표:**  프론트엔드 웹 개발 기초 다지기 (HTML, CSS, JavaScript) 및 웹 보안 기초 학습\n",
      "\n",
      "**기간:**  8주 (상황에 따라 조정 가능)\n",
      "\n",
      "**학습 플랫폼:** Udemy, Inflearn, 잔재미코딩 (선택)  YouTube (보조자료)\n",
      "\n",
      "**참고:** 본 계획은 제한된 시간(주 5시간 미만) 내에서 효율적인 학습을 목표로 합니다. 각 주차별 학습량은  자신의 학습 속도에 따라 조절해야 합니다.  \n",
      "\n",
      "\n",
      "**1주차: HTML 기초**\n",
      "\n",
      "* **목표:** HTML 기본 문법, 웹 페이지 구조 이해,  기본 태그 활용\n",
      "* **학습 자료:**\n",
      "    * Inflearn: \"초보자를 위한 HTML 기초\" 강의 (수강 시간 확인 후 선택)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 HTML 관련 부분 (무료 강의 및 체험 강의 활용)\n",
      "    * YouTube:  \"프론트엔드개발자 기초 강의 1시간 몰아보기! 이걸로 끝! 시리즈 1\" (보조 자료)\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:**  간단한 웹 페이지 제작 연습 (예: 개인 포트폴리오 페이지의 기본 구조 만들기)\n",
      "\n",
      "\n",
      "**2주차: CSS 기초**\n",
      "\n",
      "* **목표:** CSS 기본 문법, 스타일 적용 방법, 선택자 이해, 박스 모델 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn:  CSS 관련 강의 (Flex와 Grid 강의 우선 고려)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 CSS 관련 부분\n",
      "    * 잔재미코딩: \"탄탄한 프런트엔드 기본 부트캠프\" 강의 (CSS 부분, 유료 강의이므로 무료 강의와 비교 후 결정)\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:** 1주차에 제작한 웹 페이지에 CSS 적용하여 스타일링 연습\n",
      "\n",
      "\n",
      "**3주차: JavaScript 기초**\n",
      "\n",
      "* **목표:** JavaScript 기본 문법, 변수, 데이터 타입, 제어문, 함수 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn: \"자바스크립트 : 기초부터 실전까지 올인원\" 강의 (수강 시간 확인 후 선택)\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 JavaScript 관련 부분\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:**  간단한 JavaScript 스크립트 작성 연습 (예: 버튼 클릭 시 내용 변경, 간단한 계산기)\n",
      "\n",
      "\n",
      "**4주차: JavaScript 심화 (DOM 조작)**\n",
      "\n",
      "* **목표:** DOM (Document Object Model) 이해, DOM 조작을 이용한 동적 웹 페이지 구현\n",
      "* **학습 자료:**\n",
      "    * Udemy, Inflearn: JavaScript 심화 강의 (DOM 조작 관련 부분)\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:** 2, 3주차 웹 페이지에 JavaScript를 활용하여 동적 요소 추가 (예: 목록 추가, 내용 변경)\n",
      "\n",
      "\n",
      "**5주차: 반응형 웹 디자인**\n",
      "\n",
      "* **목표:** 반응형 웹 디자인 개념 이해, 미디어 쿼리 활용\n",
      "* **학습 자료:**\n",
      "    * Inflearn: 반응형 웹 기초 강의\n",
      "    * Udemy: 프론트엔드 웹 개발 강의 중 반응형 디자인 관련 부분\n",
      "* **학습 시간:** 3시간\n",
      "* **활동:**  기존 웹 페이지를 반응형으로 수정\n",
      "\n",
      "\n",
      "**6주차: 웹 보안 기초**\n",
      "\n",
      "* **목표:**  웹 보안의 기본 개념, XSS, CSRF 등 주요 공격 방식 이해, 기본적인 방어 기법 숙지\n",
      "* **학습 자료:**\n",
      "    *  KISA 아카데미 또는 정보보호교육센터의 관련 자료 (무료 강의 및 자료 활용)\n",
      "    *  Udemy, Inflearn: 웹 보안 관련 강의 (시간 제약으로 선택적으로 수강)\n",
      "* **학습 시간:** 2시간\n",
      "* **활동:**  웹 보안 관련 자료 정리 및 학습 내용 요약\n",
      "\n",
      "\n",
      "**7주차:  프론트엔드 프레임워크 소개 (React 또는 Vue.js 중 택일)**\n",
      "\n",
      "* **목표:**  React 또는 Vue.js 중 하나의 프레임워크 기본 개념 및 장단점 이해\n",
      "* **학습 자료:**\n",
      "    * Inflearn: React 또는 Vue.js 관련 입문 강의 (시간 제약으로 기본적인 개념 학습에 집중)\n",
      "* **학습 시간:** 4시간\n",
      "* **활동:**  간단한 예제 프로젝트 진행 (선택)\n",
      "\n",
      "\n",
      "**8주차: 프로젝트 및 복습**\n",
      "\n",
      "* **목표:**  지금까지 학습한 내용을 바탕으로 간단한 웹 애플리케이션 프로젝트 진행 및 복습\n",
      "* **학습 자료:**  이전 주차 학습 자료 활용\n",
      "* **학습 시간:** 5시간\n",
      "* **활동:**  프로젝트 구현 및 피드백\n",
      "\n",
      "\n",
      "**추가 학습:**\n",
      "\n",
      "*  시간이 허락한다면,  `잔재미코딩`의 \"탄탄한 프런트엔드 기본 부트캠프\" 강의를 수강하는 것을 고려해 볼 수 있습니다.  다만, 유료 강의이며, 전체 강의 시간을 확인 후 시간 계획에 맞춰 수강 여부를 결정해야 합니다.\n",
      "*  웹 개발 관련 뉴스레터 구독을 통해 최신 기술 동향을 파악하는 것도 도움이 됩니다.\n",
      "\n",
      "\n",
      "**중요 사항:** 학습 계획은 참고 자료이며, 개인의 학습 속도와 이해도에 따라 조정해야 합니다.  매주 학습 내용을 정리하고,  실제 프로젝트를 통해  학습 내용을 적용하는 것이 중요합니다.  꾸준한 학습과 실습을 통해 목표 달성을 위한 노력을 지속해야 합니다.\n",
      "\n",
      "## 검토 및 제언:\n",
      "This is a good starting point for a frontend web development learning plan.  Here are some suggestions to make it even better:\n",
      "\n",
      "**Improvements and Additions:**\n",
      "\n",
      "* **Specificity in Learning Resources:**  Instead of broadly suggesting \"Udemy/Inflearn:  JavaScript 심화 강의 (DOM 조작 관련 부분),\"  provide specific course names or links whenever possible.  This significantly increases the plan's usability.  Many Udemy and Inflearn courses have overlapping content, so recommending specific high-rated courses will improve efficiency.\n",
      "\n",
      "* **Version Control (Git):**  Integrate Git and GitHub (or GitLab, Bitbucket) into the plan.  Version control is crucial for any software developer, and it should be introduced early.  Suggest creating a GitHub repository for each project.\n",
      "\n",
      "* **Project Ideas (More Concrete):** The project suggestions are a bit vague.  Provide more specific project ideas for each week, or at least for the final project.  Examples:\n",
      "\n",
      "    * **Week 1:**  Simple HTML page with a heading, paragraph, image, and link.\n",
      "    * **Week 2:** Style the Week 1 page with CSS, focusing on layout and basic styling.\n",
      "    * **Week 3:** Add JavaScript to display a greeting based on the time of day.\n",
      "    * **Week 8:**  A to-do list app, a simple calculator, or a basic weather app (using an API).\n",
      "\n",
      "* **Debugging and Troubleshooting:** Add a section or mention within each week about debugging techniques.  This is a crucial skill for developers.  Suggest using the browser's developer tools.\n",
      "\n",
      "* **Testing:** Briefly mention the importance of testing and perhaps introduce simple testing concepts as the plan progresses.\n",
      "\n",
      "* **Accessibility:**  Include a section (perhaps in Week 5 or 6) on web accessibility best practices (WCAG).  This is becoming increasingly important.\n",
      "\n",
      "* **Time Tracking:**  Suggest a time-tracking method (app or simple spreadsheet) to monitor progress and identify areas needing more or less time.\n",
      "\n",
      "* **Portfolio Building:** Emphasize the importance of building a portfolio and suggest adding each week's project to it.  GitHub Pages is a great option for hosting a portfolio.\n",
      "\n",
      "* **Community Engagement:**  Encourage joining online communities (e.g., Stack Overflow, Discord servers for frontend development) for asking questions and learning from others.\n",
      "\n",
      "\n",
      "**Revised Week Structure Example (incorporating some suggestions):**\n",
      "\n",
      "**Week 1: HTML Fundamentals & Git Introduction**\n",
      "\n",
      "* **Goal:** Learn basic HTML syntax, create a simple webpage, and set up a Git repository.\n",
      "* **Resources:**\n",
      "    * FreeCodeCamp's Responsive Web Design Certification (HTML sections) - *Specific and well-regarded resource*\n",
      "    * **Git Tutorial:**  [Link to a good Git tutorial, e.g., GitHub's learning lab]\n",
      "* **Project:** Create a simple webpage with a heading, paragraph, image, and link.  Commit changes to your Git repository.\n",
      "\n",
      "**(Repeat similar structure for other weeks, adding more detail and specific resources.)**\n",
      "\n",
      "\n",
      "By adding these details and focusing on concrete actions, the learning plan becomes much more actionable and effective for a student.  Remember to always link to specific resources whenever possible.\n",
      "--------------------\n",
      "🤖 Agent: 대화를 종료합니다.\n"
     ]
    }
   ],
   "source": [
    "# 기존 코드의 'while True' 루프 전체를 아래 코드로 교체하세요.\n",
    "\n",
    "# ==== 2번 셀: '전문가 팀 워크플로우' 전용 실행 코드 ====\n",
    "# 새 대화를 위한 config 설정\n",
    "config = {\"configurable\": {\"thread_id\": \"workflow-convo-200011911\"}}\n",
    "\n",
    "print(\"🤖 Agent: 안녕하세요! 무엇을 도와드릴까요? (대화를 종료하려면 'quit'을 입력하세요)\")\n",
    "\n",
    "while True:\n",
    "    user_input = input(\"🧑‍💻 User: \")\n",
    "    if user_input.lower() in [\"quit\", \"exit\", \"q\"]:\n",
    "        print(\"🤖 Agent: 대화를 종료합니다.\")\n",
    "        break\n",
    "\n",
    "    # 'app' is already defined in the notebook, so we use it directly\n",
    "    events = app.stream(\n",
    "        {\"messages\": [HumanMessage(content=user_input)]}, config, stream_mode=\"values\"\n",
    "    )\n",
    "\n",
    "    final_message = None\n",
    "\n",
    "    print(\"\\n--------------------\")\n",
    "    for event in events:\n",
    "        last_message = event[\"messages\"][-1]\n",
    "\n",
    "        if isinstance(last_message, ToolMessage):\n",
    "            print(f\"🤖 Agent: ({last_message.name} 단계를 처리하고 있습니다...)\")\n",
    "        \n",
    "        final_message = last_message\n",
    "\n",
    "    if isinstance(final_message, AIMessage):\n",
    "        print(\"\\n[최종 답변]\")\n",
    "        print(\"🤖 Agent:\", final_message.content)\n",
    "    elif isinstance(final_message, ToolMessage) and final_message.name == \"generate_clarifying_question_tool\":\n",
    "        # ⭐⭐⭐ 이 부분을 수정합니다. ⭐⭐⭐\n",
    "        questions_list = json.loads(final_message.content)\n",
    "        print(\"🤖 Agent: 요청을 명확하게 하기 위해 몇 가지 질문에 답해주세요.\")\n",
    "        \n",
    "        # questions_list가 배열인지 확인하고 순회\n",
    "        if isinstance(questions_list, list):\n",
    "            for question_data in questions_list:\n",
    "                question_text = question_data.get('question', '')\n",
    "                choices_list = question_data.get('choices', [])\n",
    "                if question_text and choices_list:\n",
    "                    print(f\"\\n❓ {question_text}\")\n",
    "                    for i, choice in enumerate(choices_list):\n",
    "                        print(f\"   {i+1}. {choice}\")\n",
    "        else:\n",
    "            # 리스트가 아닌 경우 (예: 단일 객체) 기존 로직 유지 (안전성 확보)\n",
    "            question_text = questions_list.get('question', '')\n",
    "            choices_list = questions_list.get('choices', [])\n",
    "            if question_text and choices_list:\n",
    "                print(f\"\\n❓ {question_text}\")\n",
    "                for i, choice in enumerate(choices_list):\n",
    "                    print(f\"   {i+1}. {choice}\")\n",
    "\n",
    "        print(\"\\n(위 질문에 대한 답변을 다음 User 프롬프트에 입력해주세요.)\")\n",
    "\n",
    "    print(\"--------------------\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
